### ISSUE TITLE
Following readme.

### ISSUE THREAD

**Issue by iBotPeaches** [MiCode/patchrom#1]
root@gemini-server:/home/peaches/patchrom/honor# make fullota
make: **\* No rule to make target `/home/peaches/patchrom/miui/system/framework/framework.jar', needed by`apktool-if'.  Stop.
root@gemini-server:/home/peaches/patchrom/honor# 

Where are the *apks to install via apktool?

I followed the directions exactly, and add on "make fullota" it failed.

**Comment by QQ993663** [comment]
Please wait 3 more hours, the code will be ready then.

**Comment by iBotPeaches** [comment]
rewriting SYSTEM/build.prop:
    signing: CalendarProvider.apk             (/home/peaches/patchrom/build/security/testkey)
Traceback (most recent call last):
  File "/home/peaches/patchrom/tools/releasetools/sign_target_files_apks", line 354, in <module>
    main(sys.argv[1:])
  File "/home/peaches/patchrom/tools/releasetools/sign_target_files_apks", line 341, in main
    SignApks(input_zip, output_zip, apk_key_map, key_passwords)
  File "/home/peaches/patchrom/tools/releasetools/sign_target_files_apks", line 153, in SignApks
    signed_data = SignApk(data, key, key_passwords[key])
  File "/home/peaches/patchrom/tools/releasetools/sign_target_files_apks", line 131, in SignApk
    common.SignFile(unsigned.name, signed.name, keyname, pw, align=4)
  File "/home/peaches/patchrom/tools/releasetools/common.py", line 374, in SignFile
    p = Run(["zipalign", "-f", str(align), sign_name, output_name])
  File "/home/peaches/patchrom/tools/releasetools/common.py", line 62, in Run
    return subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.6/subprocess.py", line 633, in **init**
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1139, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

It worked :)

With that random warning/error during the signing.

**Comment by MiuiInter** [comment]
You need to add android SDK tools/platform-tools to your path

**Comment by iBotPeaches** [comment]
I'm not an idiot when it comes to this stuff, but for the life of me I cannot get any of the demos to build. I just repo sync-ed and just tried "make fullota"

/home/peaches/patchrom/tools/remove_redef.py >/dev/null out/framework-res
/home/peaches/patchrom/tools/apktool --quiet b out/framework-res out/framework-res.apk
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-sw600dp-w1024dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-w480dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-sw600dp-w1280dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-sw600dp-land
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-w600dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/drawable-sw600dp-mdpi
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-w720dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/layout-w600dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/layout-sw600dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-w500dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-sw600dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-w360dp
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/drawable-sw600dp-hdpi
invalid resource directory name: /home/peaches/patchrom/honor/out/framework-res/res/values-h720dp
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL6380960362756388714.tmp, -x, -S, /home/peaches/patchrom/honor/out/framework-res/res, -M, /home/peaches/patchrom/honor/out/framework-res/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
    at brut.androlib.Androlib.buildResources(Androlib.java:248)
    at brut.androlib.Androlib.build(Androlib.java:171)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL6380960362756388714.tmp, -x, -S, /home/peaches/patchrom/honor/out/framework-res/res, -M, /home/peaches/patchrom/honor/out/framework-res/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:83)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
    ... 6 more
make: **\* [out/framework-res.apk] Error 1
peaches@peaches-P150HMx:~/patchrom/honor$

**Comment by iBotPeaches** [comment]
I've tried the procedure on 2 different OSes now. CentOS and Ubuntu with same results. Can you build the demos using the method you provided? If so, what OS and stuff?

Here is some documentation fixes.

```
export PATH=$PATH:/home/xxx/android-sdk/tools:/home/xxx/anroid-sdk/platform-tools
```

Should be 

```
export PATH=$PATH:/home/xxx/android-sdk/tools:/home/xxx/android-sdk/platform-tools
```

Minor grammar change.
Assumed current directory is patchtom and you want to build the ROM for Huawei Honor
Assumed current directory is patchrom and you want to build the ROM for Huawei Honor
