### ISSUE TITLE
ERROR: couldn't find ro.build.fingerprint in build.prop

### ISSUE THREAD

**Issue by a937287837** [MiCode/patchrom#102]
NOT signing: GoogleContactsSyncAdapter.apk
NOT signing: DMAgent.apk
NOT signing: BasicDreams.apk
NOT signing: GoogleCamera.apk
NOT signing: CloudPrint.apk
NOT signing: Protips.apk
NOT signing: Drive.apk
    signing: framework-res.apk                            (/home/seaers/patchrom/build/security/platform)
rewriting SYSTEM/build.prop:
Traceback (most recent call last):
  File "/home/seaers/patchrom/tools/releasetools/sign_target_files_apks", line 354, in <module>
    main(sys.argv[1:])
  File "/home/seaers/patchrom/tools/releasetools/sign_target_files_apks", line 341, in main
    SignApks(input_zip, output_zip, apk_key_map, key_passwords)
  File "/home/seaers/patchrom/tools/releasetools/sign_target_files_apks", line 162, in SignApks
    new_data = RewriteProps(data)
  File "/home/seaers/patchrom/tools/releasetools/sign_target_files_apks", line 194, in RewriteProps
    assert len(pieces) == 5
AssertionError
Build full ota package: /home/seaers/patchrom/m8/out/fullota.zip
unzipping target target-files...
Warning: could not find SYSTEM/build.prop in <built-in function zip>

   ERROR: couldn't find ro.build.fingerprint in build.prop

/home/seaers/patchrom/build/porting.mk:425: recipe for target 'fullota' failed
make: **\* [fullota] Error 1

**Comment by ze00** [comment]
append "ro.build.fingerprint" into build.prop

**Comment by a937287837** [comment]
@zerozakiGeek but there is the "ro.build.fingerprint"  on build.prop

**Comment by ze00** [comment]
@a937287837 You should to modify target_files***.zip

**Comment by a937287837** [comment]
@zerozakiGeek there is the "ro.build.fingerprint" on build.prop in target_files.zip and target_files 
this is my  build.prop
` #####VZW-SPECIFIC-PROPS#####
ro.product.name=HTCOneM8vzw
ro.product.model=HTC6525LVW
ro.product.device=htc_m8wl
ro.build.product=htc_m8wl
ro.ril.oem.ecclist=911,*911,#911
ro.ril.enable.a52=0
ro.ril.enable.a53=1
ro.ril.enable.dtm=0
ro.ril.gprsclass=12
ro.ril.hsdpa.category=14
ro.ril.hsupa.category=6
ro.ril.hsxpa=4
ro.ril.att.feature=0
ro.ril.disable.fd.plmn.prefix=23402,23410,23411,23420
ro.ril.enable.managed.roaming=1
ro.ril.enable.sdr=0
ro.ril.oem.show.act=0
ro.ril.enable.gea3=1
ro.ril.set.mtusize=1428
ro.ril.enable.r8fd=1
ro.ril.disable.cpc=1
ro.ril.air.enabled=0
ro.ril.vzw.feature=1
ro.ril.wp.feature=1
ro.cdma.data_retry_config=max_retries=infinite,0,0,60000,120000,480000,900000
ro.config.svlte1x=true
ro.ril.gsm.to.lte.blind.redir=0
ro.product.locale.language=en
ro.product.locale.region=US
ro.product.locale=en-US
ro.com.google.clientidbase=android-htc
ro.com.google.clientidbase.yt=android-verizon
ro.com.google.clientidbase.am=android-verizon
ro.com.google.clientidbase.gmm=android-htc
ro.com.google.clientidbase.ms=android-verizon
ro.phone.save_timer=10000
ro.cdma.home.operator.alpha=Verizon
gsm.sim.operator.alpha=Verizon
gsm.operator.alpha=Verizon
ro.cdma.home.operator.numeric=310012
gsm.sim.operator.numeric=310012
gsm.operator.numeric=310012
ro.net.apnwhitelist=fota,ims,supl,verizon,verizon800,cbs,mms
ro.net.apnroamingwhitelist=ims
ro.net.apnpolicywhitelist=fota,ims,verizon,verizon800
ro.net.apnroamingblacklist=fota,verizon800
ro.config.htc.nocheckin=0
ro.HorizontalVVM=true
ro.HorizontalBUA=true
ro.telephony.ipv6_capability=1
ro.ril.pdpnumber.policy.roaming=3
ro.gsm.data_retry_config=max_retries=infinite,0,0,60000,120000,480000,900000
ro.gsm.2nd_data_retry_config=max_retries=infinite,0,0,60000,120000,480000,900000
ro.ril.fast.dormancy.cdma.rule=0
ro.net.smd=0
ro.st.agg=true
ro.socialap.vzwcustomization=true
ro.apn.ui.hide_add=0
ro.apn.ui.hide_delete=0
ro.cw.base.version=M60
telephony.lteOnCdmaDevice=1
ro.telephony.default_network=10
persist.radio.snapshot_enabled = 1
persist.radio.snapshot_timer = 22
persist.cne.UseCne=vendor
persist.cne.UseSwim=false
persist.cne.bat.range.low.med=30
persist.cne.bat.range.med.high=60
persist.cne.loc.policy.op=/system/etc/OperatorPolicy.xml
persist.cne.loc.policy.user=/system/etc/UserPolicy.xml
persist.cne.bwbased.rat.sel=false
persist.cne.snsr.based.rat.mgt=false
persist.cne.bat.based.rat.mgt=false
persist.cne.rat.acq.time.out=30000
persist.cne.rat.acq.retry.tout=0
persist.cne.sync.swim.mode=false
ro.gps.agps_provider=1
#ro.cdma.homesystem=64,65,76,77,78,79,80,81,82,83
#####END-SPECIFIC-PROPS#####

# begin build properties

# autogenerated by buildinfo.sh

htc.build.stage=2
ro.aa.cidlist=GOOGL001,11111111,CWS__001,T-MOB010
ro.aa.modelid=0P6B10000,0P6B12000,0P6B13000,0P6B11000,0P6B15000,0P6B16000,0P6B17000
ro.aa.skulist=1700
ro.aa.report=com
ro.aa.maincid=GOOGL001
ro.onecid=
ro.aa.project=M8_UL_M60_STOCK_UI_MR
ro.aa.romver=5.07.1700.15
ro.aa.mainsku=0
ro.cwkey=GOOGL001
ro.aa.customizationid=N/A
ro.prot=true
ro.aa.taskid=482419
ro.aa.rid=53
ro.build.id=MRA58K.H15
ro.build.display.id=MRA58K.H15 release-keys
ro.build.version.incremental=02.20161004.120935
ro.build.version.sdk=23
ro.build.version.preview_sdk=0
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=6.0
ro.build.version.security_patch=2016-07-01
ro.build.version.base_os=
ro.build.date=三  7月 20 17:20:56 CST 2016
ro.build.date.utc=1469006456
ro.build.type=user
ro.build.user=buildteam
ro.build.host=ABM102
ro.build.tags=release-keys
ro.build.flavor=htc_m8-user
ro.product.model=HTC One_M8
ro.product.brand=htc
ro.product.name=m8_google
ro.product.device=htc_m8
ro.product.board=MSM8974

# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,

# use ro.product.cpu.abilist instead.

ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.cpu.abilist=armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=
ro.product.manufacturer=HTC
ro.product.locale=en-AU
ro.wifi.channels=
ro.board.platform=msm8974

# ro.build.product is obsolete; use ro.product.device

ro.build.product=htc_m8

# Do not try to parse description, fingerprint, or thumbprint

ro.build.description=5.07.1700.15 CL648564 release-keys
ro.build.fingerprint=htc/m8_google/htc_m8:6.0/MRA58K.H15/666676:user/release-keys
ro.build.characteristics=default
ro.build.description=5.07.1700.15 CL648564 release-keys

# Do not try to parse ro.build.description or .fingerprint

ro.build.description=5.07.1700.15 CL648564 release-keys
ro.build.changelist=648564
ro.build.project=M8_UL_M60_STOCK_UI_MR:482419
ro.build.sku=
ro.build.buildline=M8UL_Generic_WWE_M60_CRC_StockUI_MR
ro.product.version=5.07.1700.15
ro.build.languageremove=
ro.build.sense.version=
Error of ro.build.version.htcsdk.
ro.build.chinasense=

# end build properties

#

# from device/htc/htc_m8/system.prop

#
#

# system.prop for msm8974

#

rild.libpath=/vendor/lib/libril-qc-qmi-1.so
rild.libargs=-d /dev/smd0
persist.rild.nitz_plmn=
persist.rild.nitz_long_ons_0=
persist.rild.nitz_long_ons_1=
persist.rild.nitz_long_ons_2=
persist.rild.nitz_long_ons_3=
persist.rild.nitz_short_ons_0=
persist.rild.nitz_short_ons_1=
persist.rild.nitz_short_ons_2=
persist.rild.nitz_short_ons_3=
ril.subscription.types=NV,RUIM
DEVICE_PROVISIONED=1

# Default network type.

# 9 => GSM/UMTS/LTE mode preferred.

ro.telephony.default_network=9

#

# system props for display

#
debug.sf.hw=1
debug.egl.hw=1
debug.composition.type=gpu
persist.hwc.mdpcomp.enable=true
ro.hwui.renderer.disable_opaque=true
ro.sf.lcd_density=480
debug.mdpcomp.logs=0

# Display Info

ro.product.display_resolution = 5 inch 1080p resolution

dalvik.vm.heapsize=512m
dalvik.vm.heapgrowthlimit=192m
dalvik.vm.heapstartsize=8m
dalvik.vm.heapmaxfree=8m
dalvik.vm.heapminfree=2m

dev.pm.dyn_samplingrate=1
persist.demo.hdmirotationlock=false

# +SSD_RIL

ro.baseband.arch=msm

# -SSD_RIL

# Enable IMS service by default

persist.radio.jbims=1

ro.hdmi.enable=true
tunnel.decode=true
tunnel.audiovideo.decode=true
lpa.decode=true
lpa.use-stagefright=true
persist.speaker.prot.enable=false
qcom.hw.aac.encoder=true
use.voice.path.for.pcm.voip=true
#

# system props for the cne module

#
persist.cne.feature=1

#system props for the MM modules

media.stagefright.enable-player=true
media.stagefright.enable-http=true
media.stagefright.enable-aac=true
media.stagefright.enable-qcp=true
media.stagefright.enable-fma2dp=true
media.stagefright.enable-scan=true
mmp.enable.3g2=true
mm.enable.smoothstreaming=true
media.aac_51_output_enabled=true
#37491 is decimal sum of supported codecs in AAL
#codecs: AVI AC3 ASF AAC QCP DTS 3G2 MP2TS
mm.enable.qcom_parser=37491

# VIDC: debug_levels

# 1:ERROR 2:HIGH 4:LOW 0:NOLOGS 7:AllLOGS

vidc.debug.level=3
#

# system props for the data modules

#
ro.use_data_netmgrd=true
persist.data.netmgrd.qos.enable=false
ro.data.large_tcp_window_size=true

#system props for time-services
persist.timed.enable=true

# System props for audio

# System props for soundhound

# Audio TODO: Temp removed .samplerate for system prop name length limit in

# build/tools/post_process_props.py since L-release

# persist.htc.audio.pcm.samplerate=48000

persist.htc.audio.pcm.channels=2

# System prop to select audio resampler quality

# af.resampler.quality=4

# System props for global effect

htc.audio.global.state=0
htc.audio.global.profile=0
htc.audio.q6.topology=0
htc.audio.global.speaker=1
htc.audio.srs.defaultbundleHS=MAX300
#

# system prop for opengles version

#

# 196608 is decimal for 0x30000 to report version 3

ro.opengles.version=196608

#

# system prop for Bluetooth Dialup Networking

#
ro.qualcomm.bluetooth.dun=false

# system prop for Bluetooth FTP profile

ro.qualcomm.bluetooth.ftp=true
#

# system property for Bluetooth Handsfree Profile Wide Band Speech

#
ro.qualcomm.bluetooth.hfp.wbs=false
#
#system prop for Bluetooth hci transport
ro.qualcomm.bt.hci_transport=smd
#

# system prop for requesting Master role in incoming Bluetooth connection.

#
ro.bluetooth.request.master=true
#

# system prop for Bluetooth Auto connect for remote initated connections

#
ro.bluetooth.remote.autoconnect=true

# system property for Bluetooth discoverability time out in seconds

# 0: Always discoverable

#debug.bt.discoverable_time=0

# system property for Bluetooth Hardware information

ro.product.bluetooth=4.0

# config fm rssi threshold

#service.qct.fm.rssi=116
#SSD_BT- bluetooth

# system property for qcom Bluetooth stack

ro.qc.bluetooth.stack=bluedroid

# BLE TAG (HtcBluetoothLeProfiles)

ro.bt.ble_tag = 1

# Bluetooth address

ro.bt.bdaddr_path = /sys/module/htc_bdaddress/parameters/bdaddress

# System property for cabl

#ro.qualcomm.cabl=1

#

# System props for telephony

# System prop to turn on CdmaLTEPhone always

#+ SSD_RIL: disable default value by MASD request
#telephony.lteOnCdmaDevice=1
#- SSD_RIL: disable default value by MASD request

#Simulate sdcard on /data/media
#
persist.fuse_sdcard=true

# ro.storage_structure: define the storage structure of this project

# FUSE: 0x8, FAT: 0x4, SD: 0x2, INS: 0x1

# Example: If the project has FUSE with SD card, the value should be defined as 10 (dec)

ro.storage_structure = 10

# ro.storage_encryption_type: define the storage encryption type of this project

# not support encryption: 0x0 block level: 0x1 file level: 0x2

ro.storage_encryption_type = 2
#For usb storage
ro.usb_host = 1
#
#snapdragon value add features
#
ro.qc.sdk.audio.ssr=false
##fluencetype can be "fluence" or "fluencepro" or "none"
ro.qc.sdk.audio.fluencetype=none
ro.qc.sdk.sensors.gestures=true
ro.qc.sdk.gestures.camera=false
ro.qc.sdk.camera.facialproc=false
#property to enable user to access Google WFD settings.
persist.debug.wfd.enable=1
#property to choose between virtual/external wfd display
persist.sys.wfd.virtual=0
#propery to enable VDS WFD solution
persist.hwc.enable_vds=1

# Following property will be reference by Settings.

ro.product.main_camera =HTC UltraPixel Camera
ro.product.front_camera = 5M

# Support HW rest

ro.product.hwreset = 1
ro.product.hwreset.timer1 = 6
ro.product.hwreset.timer2 = 9

# M8 HW info

ro.product.ram = 2GB

# wifi

wifi.softap.interface=wlan0
wifi.softapconcurrent.interface=softap.0
wifi.miracastconcurrent.scan=WCN3680
init.svc.wpa_supplicant=
init.svc.dhcpcd_wlan0=
dhcp.wlan0.autoip=
dhcp.wlan0.dns1=
dhcp.wlan0.dns2=
dhcp.wlan0.dns3=
dhcp.wlan0.dns4=
dhcp.wlan0.gateway=
dhcp.wlan0.ipaddress=
dhcp.wlan0.leasetime=
dhcp.wlan0.mask=
dhcp.wlan0.ooxx=
dhcp.wlan0.pid=
dhcp.wlan0.reason=
dhcp.wlan0.result=
dhcp.wlan0.server=
net.wlan0.dns1=
net.wlan0.dns2=
wifi.wpa_supp_ready=
wlan.driver.status=
wifi.interface=wlan0
wifi.supplicant_scan_interval=15
persist.wifi.v6=true
persist.wifi.v6.rs.count=5
persist.wifi.v6.rs.timeout=5
ro.product.wifi = 802.11 a/b/g/n/ac
tunnel.audio.encode = false

# For Embadded DIAG

ro.chipset.vendor=QCT
ro.chipset.model=MSM8974
ro.chipset.version=1.x

# ro.storage_encryption_type: define the storage encryption type of this project

# not support encryption: 0x0 block level: 0x1 file level: 0x2

ro.storage_encryption_type = 2

# For VOLD storage master key encryption algorithm scrypt

ro.crypto.scrypt_params=16:3:1

#

# ADDITIONAL_BUILD_PROPERTIES

#
ro.com.google.clientidbase=android-google
ro.config.ringtone=Ring_Synth_04.ogg
ro.config.notification_sound=pixiedust.ogg
ro.config.alarm_alert=Alarm_Classic.ogg
ro.sys.medialink=0
ro.ril.hsdpa.category=14
ro.ril.hsupa.category=6
ro.ril.hsxpa=4
ro.ril.radio.svn=1
ro.ril.disable.cpc=1
ro.ril.def.agps.mode=1
keyguard.no_require_sim=true
ro.com.android.dataroaming=false
ro.carrier=unknown
drm.service.enabled=true
ro.com.android.mobiledata=true
ro.setupwizard.mode=OPTIONAL
ro.com.google.gmsversion=6.0_r1
dalvik.vm.heapstartsize=8m
dalvik.vm.heapgrowthlimit=192m
dalvik.vm.heapsize=512m
dalvik.vm.heaptargetutilization=0.75
dalvik.vm.heapminfree=2m
dalvik.vm.heapmaxfree=8m
ro.vendor.extension_library=/vendor/lib/libqc-opt.so
persist.radio.apm_sim_not_pwdn=1
persist.sys.dalvik.vm.lib.2=libart
dalvik.vm.isa.arm.variant=krait
dalvik.vm.isa.arm.features=default
net.bt.name=Android
dalvik.vm.stack-trace-file=/data/anr/traces.txt
ro.expect.recovery_id=0x81a1de9632d446ce62485c03dda4a334244ab981000000000000000000000000
ro.miui.ui.version.code=5
ro.miui.ui.version.name=V8
ro.config.sms_received_sound=FadeIn.ogg
ro.config.sms_delivered_sound=MessageComplete.ogg
persist.sys.strictmode.disable=true
ro.product.mod_device=Unknown`

**Comment by imFaa** [comment]
@a937287837 
hi did you solved ro..build.fingerprint not found problem?

**Comment by viksok** [comment]
farooque7508, I did. Just modify like this and pack to your target_files/SYSTEM.zip

`ro.build.fingerprint=motorola/titan/XT1068:6.0.1/MOB30Z/f6a66ca74f:userdebug/test-keys`

Made it mostly of ro.build.display.id

**Comment by imFaa** [comment]
@a937287837 but your build.prop says your device is HTC and you modified to.build.fingerprint says Motorola/titan
So should I do the same or I have to modify as per my device..actually I have ro.build.fingerprint in my build.prop with the same line as you said but still it says ro.fingerprint not found.?

**Comment by JustRlx93** [comment]
Hi all, i'm too had this problem, when i tried "../tools/releasetools/ota_target_from_phone -r" Konsole says:
Compress the target_files dir into zip file
/home/rlx/patchrom/xblade
Build full ota package: /home/rlx/patchrom/xblade/stockrom.zip
unzipping target target-files...

   ERROR: couldn't find ro.build.fingerprint in build.prop

> farooque7508, I did. Just modify like this and pack to your target_files/SYSTEM.zip
> 
> ro.build.fingerprint=motorola/titan/XT1068:6.0.1/MOB30Z/f6a66ca74f:userdebug/test-keys
> 
> Made it mostly of ro.build.display.id

Could you explain better, where (path to directory) i need to go and what exactly to do on the items?
Tried to replace the file in the archive, modify the contents of the file (the error occurs when i try to save) - did not help.

**Comment by imFaa** [comment]
@JustRlx93 you have to put some scripts in device golder before pulling files from phone to do that
1-download and edit all scripts as per your device and put all in your device folder

2- now extract your ROM and get build.prop and edit as mentioned above

3- no give command to pull files from your device and keep watching in device/out/Target_files/SYSTEM directory onece build.prop is pulled just copy paste edited build.prop there.for detail guide refer to this video on YouTube.


https://youtu.be/gy7GgXPd6dg

**Comment by zeinalarif** [comment]
i was follow u video but same i stuck here my device was root and adb devices check work fine
see this terminal report
zein@zein:~/bin/patchrom$ cd /home/zein/bin/patchrom
zein@zein:~/bin/patchrom$ . build/envsetup.sh
PATCHROM_BRANCH  = marshmallow
ANDROID_PLATFORM = 23
PORT_ROOT        = /home/zein/bin/patchrom
ANDROID_TOP      = 
ANDROID_OUT      = 
PORT_PRODUCT     = Unknown
USE_ANDROID_OUT  = 
ANDROID_BRANCH   = 
HOST_OS          = linux
zein@zein:~/bin/patchrom$ cd ferrari
zein@zein:~/bin/patchrom/ferrari$ ../tools/releasetools/ota_target_from_phone -nWait for the device to be online...
Copy target file template into current working directory
Warning: the ota package will not contain bootimage!!!
Maybe you forget to pass the ota-package parameter.
Are you sure this is really what you want(yes/no):yes
Build recovery.fstab from device
Extract the whole /system from device
[ 44%] /system/vendor/lib/libchromatix_imx134_default_video.so: 100%
Remount /system to be writable
adb: unable to connect for root: no devices/emulators found
error: no devices/emulators found
Run getfilesysteminfo to build filesystem_config.txt
/home/zein/bin/patchrom/tools/target_f...ed. 2.9 MB/s (1165484 bytes in 0.381s)
system 0 0 755 selabel=u:object_r:system_file:s0 capabilities=0x0
system/build.prop 0 0 644 selabel=u:object_r:system_file:s0 capabilities=0x0
system/recovery-from-boot.bak 0 0 644 selabel=u:object_r:system_file:s0 capabilities=0x0
system/lstat'/system/rfs'failed:Permissiondenied stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory selabel=u:lstat capabilities=0x0
system//system/rfs:Permissiondenied stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory selabel=u:/system/rfs: capabilities=0x0
Run getfilesysteminfo and recoverylink.py to recover symlink
system/lstat '/system/rfs' failed: Permission denied|BusyBox v1.20.2-MIUI (2012-08-20 20:59:32 CST) multi-call binary.

Usage: readlink [-fnv] FILE

Display the value of a symlink

	-f	Canonicalize by following all symlinks
	-n	Don't add newline
	-v	Verbose
Traceback (most recent call last):
  File "/home/zein/bin/patchrom/tools/releasetools/recoverylink.py", line 16, in <module>
    target = filepath[1]
IndexError: list index out of range
rm: /system/xbin/getfilesysteminfo: No such file or directory
Build apkcerts.txt
adb: error: failed to copy '/data/system/packages.xml' to '/home/zein/bin/patchrom/ferrari/out/target_files/packages.xml': remote Permission denied
Error: /home/zein/bin/patchrom/ferrari/out/target_files/packages.xml doesn't exist or isn't a vaild xml file
ls: cannot access /home/zein/bin/patchrom/ferrari/out/target_files/SYSTEM/framework/*.apk: No such file or directory
rm: cannot remove `/home/zein/bin/patchrom/ferrari/out/target_files/packages.xml': No such file or directory
Generate metadata used to build target files...
Decode oat files
Compress the target_files dir into zip file
/home/zein/bin/patchrom/ferrari
Build full ota package: /home/zein/bin/patchrom/ferrari/stockrom.zip
unzipping target target-files...

   ERROR: couldn't find ro.build.fingerprint in build.prop

zein@zein:~/bin/patchrom/ferrari$

**Comment by zeinalarif** [comment]
i was follow u video but same i stuck here my device was root and adb devices check work fine
see this terminal report
zein@zein:~/bin/patchrom$ cd /home/zein/bin/patchrom
zein@zein:~/bin/patchrom$ . build/envsetup.sh
PATCHROM_BRANCH  = marshmallow
ANDROID_PLATFORM = 23
PORT_ROOT        = /home/zein/bin/patchrom
ANDROID_TOP      = 
ANDROID_OUT      = 
PORT_PRODUCT     = Unknown
USE_ANDROID_OUT  = 
ANDROID_BRANCH   = 
HOST_OS          = linux
zein@zein:~/bin/patchrom$ cd ferrari
zein@zein:~/bin/patchrom/ferrari$ ../tools/releasetools/ota_target_from_phone -nWait for the device to be online...
Copy target file template into current working directory
Warning: the ota package will not contain bootimage!!!
Maybe you forget to pass the ota-package parameter.
Are you sure this is really what you want(yes/no):yes
Build recovery.fstab from device
Extract the whole /system from device
[ 44%] /system/vendor/lib/libchromatix_imx134_default_video.so: 100%
Remount /system to be writable
adb: unable to connect for root: no devices/emulators found
error: no devices/emulators found
Run getfilesysteminfo to build filesystem_config.txt
/home/zein/bin/patchrom/tools/target_f...ed. 2.9 MB/s (1165484 bytes in 0.381s)
system 0 0 755 selabel=u:object_r:system_file:s0 capabilities=0x0
system/build.prop 0 0 644 selabel=u:object_r:system_file:s0 capabilities=0x0
system/recovery-from-boot.bak 0 0 644 selabel=u:object_r:system_file:s0 capabilities=0x0
system/lstat'/system/rfs'failed:Permissiondenied stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory selabel=u:lstat capabilities=0x0
system//system/rfs:Permissiondenied stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory selabel=u:/system/rfs: capabilities=0x0
Run getfilesysteminfo and recoverylink.py to recover symlink
system/lstat '/system/rfs' failed: Permission denied|BusyBox v1.20.2-MIUI (2012-08-20 20:59:32 CST) multi-call binary.

Usage: readlink [-fnv] FILE

Display the value of a symlink

	-f	Canonicalize by following all symlinks
	-n	Don't add newline
	-v	Verbose
Traceback (most recent call last):
  File "/home/zein/bin/patchrom/tools/releasetools/recoverylink.py", line 16, in <module>
    target = filepath[1]
IndexError: list index out of range
rm: /system/xbin/getfilesysteminfo: No such file or directory
Build apkcerts.txt
adb: error: failed to copy '/data/system/packages.xml' to '/home/zein/bin/patchrom/ferrari/out/target_files/packages.xml': remote Permission denied
Error: /home/zein/bin/patchrom/ferrari/out/target_files/packages.xml doesn't exist or isn't a vaild xml file
ls: cannot access /home/zein/bin/patchrom/ferrari/out/target_files/SYSTEM/framework/*.apk: No such file or directory
rm: cannot remove `/home/zein/bin/patchrom/ferrari/out/target_files/packages.xml': No such file or directory
Generate metadata used to build target files...
Decode oat files
Compress the target_files dir into zip file
/home/zein/bin/patchrom/ferrari
Build full ota package: /home/zein/bin/patchrom/ferrari/stockrom.zip
unzipping target target-files...

   ERROR: couldn't find ro.build.fingerprint in build.prop

zein@zein:~/bin/patchrom/ferrari$

**Comment by zeinalarif** [comment]
i was follow u video but same i stuck here my device was root and adb devices check work fine
see this terminal report
zein@zein:~/bin/patchrom$ cd /home/zein/bin/patchrom
zein@zein:~/bin/patchrom$ . build/envsetup.sh
PATCHROM_BRANCH  = marshmallow
ANDROID_PLATFORM = 23
PORT_ROOT        = /home/zein/bin/patchrom
ANDROID_TOP      = 
ANDROID_OUT      = 
PORT_PRODUCT     = Unknown
USE_ANDROID_OUT  = 
ANDROID_BRANCH   = 
HOST_OS          = linux
zein@zein:~/bin/patchrom$ cd ferrari
zein@zein:~/bin/patchrom/ferrari$ ../tools/releasetools/ota_target_from_phone -nWait for the device to be online...
Copy target file template into current working directory
Warning: the ota package will not contain bootimage!!!
Maybe you forget to pass the ota-package parameter.
Are you sure this is really what you want(yes/no):yes
Build recovery.fstab from device
Extract the whole /system from device
[ 44%] /system/vendor/lib/libchromatix_imx134_default_video.so: 100%
Remount /system to be writable
adb: unable to connect for root: no devices/emulators found
error: no devices/emulators found
Run getfilesysteminfo to build filesystem_config.txt
/home/zein/bin/patchrom/tools/target_f...ed. 2.9 MB/s (1165484 bytes in 0.381s)
system 0 0 755 selabel=u:object_r:system_file:s0 capabilities=0x0
system/build.prop 0 0 644 selabel=u:object_r:system_file:s0 capabilities=0x0
system/recovery-from-boot.bak 0 0 644 selabel=u:object_r:system_file:s0 capabilities=0x0
system/lstat'/system/rfs'failed:Permissiondenied stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system/lstat': No such file or directory
stat: can't stat '/system/rfs': Permission denied
stat: can't stat 'failed:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory selabel=u:lstat capabilities=0x0
system//system/rfs:Permissiondenied stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory stat: can't stat '/system//system/rfs:': No such file or directory
stat: can't stat 'Permission': No such file or directory
stat: can't stat 'denied': No such file or directory selabel=u:/system/rfs: capabilities=0x0
Run getfilesysteminfo and recoverylink.py to recover symlink
system/lstat '/system/rfs' failed: Permission denied|BusyBox v1.20.2-MIUI (2012-08-20 20:59:32 CST) multi-call binary.

Usage: readlink [-fnv] FILE

Display the value of a symlink

	-f	Canonicalize by following all symlinks
	-n	Don't add newline
	-v	Verbose
Traceback (most recent call last):
  File "/home/zein/bin/patchrom/tools/releasetools/recoverylink.py", line 16, in <module>
    target = filepath[1]
IndexError: list index out of range
rm: /system/xbin/getfilesysteminfo: No such file or directory
Build apkcerts.txt
adb: error: failed to copy '/data/system/packages.xml' to '/home/zein/bin/patchrom/ferrari/out/target_files/packages.xml': remote Permission denied
Error: /home/zein/bin/patchrom/ferrari/out/target_files/packages.xml doesn't exist or isn't a vaild xml file
ls: cannot access /home/zein/bin/patchrom/ferrari/out/target_files/SYSTEM/framework/*.apk: No such file or directory
rm: cannot remove `/home/zein/bin/patchrom/ferrari/out/target_files/packages.xml': No such file or directory
Generate metadata used to build target files...
Decode oat files
Compress the target_files dir into zip file
/home/zein/bin/patchrom/ferrari
Build full ota package: /home/zein/bin/patchrom/ferrari/stockrom.zip
unzipping target target-files...

   ERROR: couldn't find ro.build.fingerprint in build.prop

zein@zein:~/bin/patchrom/ferrari$
