### ISSUE TITLE
Make fullota problem how can it be solved?

### ISSUE THREAD

**Issue by imFaa** [MiCode/patchrom#106]
`/home/faa/patchrom/tools/apktool --quiet b out/framework -o out/framework.jar
out/framework/smali/com/android/internal/os/Zygote.smali[3,0] The file must contain a .class directive
Exception in thread "main" brut.androlib.AndrolibException: java.util.concurrent.ExecutionException: brut.androlib.AndrolibException: Could not smali file: com/android/internal/os/Zygote.smali
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:129)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:69)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:376)
    at brut.androlib.Androlib.buildSources(Androlib.java:335)
    at brut.androlib.Androlib.build(Androlib.java:292)
    at brut.androlib.Androlib.build(Androlib.java:268)
    at brut.apktool.Main.cmdBuild(Main.java:224)
    at brut.apktool.Main.main(Main.java:84)
Caused by: java.util.concurrent.ExecutionException: brut.androlib.AndrolibException: Could not smali file: com/android/internal/os/Zygote.smali
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:124)
    ... 7 more
Caused by: brut.androlib.AndrolibException: Could not smali file: com/android/internal/os/Zygote.smali
    at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:142)
    at brut.androlib.src.SmaliBuilder.access$000(SmaliBuilder.java:64)
    at brut.androlib.src.SmaliBuilder$1.call(SmaliBuilder.java:98)
    at brut.androlib.src.SmaliBuilder$1.call(SmaliBuilder.java:94)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
out/framework/smali/com/android/internal/os/RuntimeInit.smali[576,0] The file must contain a .class directive
out/framework/smali/android/view/WindowManager$LayoutParams.smali[2,0] The file must contain a .class directive
out/framework/smali/android/view/SurfaceControl.smali[31,0] The file must contain a .class directive
out/framework/smali/android/view/MotionEvent.smali[24,0] The file must contain a .class directive
out/framework/smali/android/view/View.smali[2,0] The file must contain a .class directive
out/framework/smali/android/view/ThreadedRenderer.smali[3,0] The file must contain a .class directive
out/framework/smali/android/view/Window.smali[101,0] The file must contain a .class directive
out/framework/smali/android/view/WindowManagerPolicy.smali[3,0] The file must contain a .class directive
out/framework/smali/android/view/Surface.smali[14,0] The file must contain a .class directive`

**Comment by Anandnv** [comment]
i just got the same issue

out/framework/smali/com/android/internal/os/Zygote.smali[3,0] The file must contain a .class directive
then it just exited

**Comment by omarilzz** [comment]
same :( out/framework/smali/android/view/Window.smali[101,0] The file must contain a .class directive

**Comment by imFaa** [comment]
@omarilzz you did a wrong patch may be that's why it is showing this error.
