### ISSUE TITLE
Memory error (Stock Rom Create Fail)

### ISSUE THREAD

**Issue by Mohi1117** [MiCode/patchrom#115]
`rm: can't remove '/system/xbin/getfilesysteminfo': No such file or directory
Build apkcerts.txt
1493 KB/s (426099 bytes in 0.278s)
Generate metadata used to build target files...
Decode oat files
Compress the target_files dir into zip file
/media/alfaris/7E68235D68231405/patchrom/lettuce
Build full ota package: /media/alfaris/7E68235D68231405/patchrom/lettuce/stockrom.zip
unzipping target target-files...
unable to load device-specific module; assuming none
using prebuilt boot.img from BOOTABLE_IMAGES...
Traceback (most recent call last):
  File "/media/alfaris/7E68235D68231405/patchrom/tools/releasetools/ota_from_target_files", line 1792, in <module>
    main(sys.argv[1:])
  File "/media/alfaris/7E68235D68231405/patchrom/tools/releasetools/ota_from_target_files", line 1747, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/media/alfaris/7E68235D68231405/patchrom/tools/releasetools/ota_from_target_files", line 630, in WriteFullOTAPackage
    OPTIONS.input_tmp, "BOOT")
  File "/media/alfaris/7E68235D68231405/patchrom/tools/releasetools/common.py", line 419, in GetBootableImage
    return File.FromLocalFile(name, prebuilt_path)
  File "/media/alfaris/7E68235D68231405/patchrom/tools/releasetools/common.py", line 1055, in FromLocalFile
    data = f.read()
MemoryError
`
any help will be appreciated

**Comment by Mohi1117** [comment]
[http://hastebin.com/jegomikupe.sql](url)
a better look at the error
