### ISSUE TITLE
Stockrom Memory error

### ISSUE THREAD

**Issue by ultimateproger** [MiCode/patchrom#116]
unzipping target target-files...
unable to load device-specific module; assuming none
using prebuilt boot.img from BOOTABLE_IMAGES...
Traceback (most recent call last):
  File "/home/user/patchrom/tools/releasetools/ota_from_target_files", line 1792, in <module>
    main(sys.argv[1:])
  File "/home/user/patchrom/tools/releasetools/ota_from_target_files", line 1747, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/user/patchrom/tools/releasetools/ota_from_target_files", line 630, in WriteFullOTAPackage
    OPTIONS.input_tmp, "BOOT")
  File "/home/user/patchrom/tools/releasetools/common.py", line 419, in GetBootableImage
    return File.FromLocalFile(name, prebuilt_path)
  File "/home/user/patchrom/tools/releasetools/common.py", line 1055, in FromLocalFile
    data = f.read()
MemoryError

What should I do?

**Comment by Mohi1117** [comment]
by little help from my friend,  i have learned that u need to increase swap for memory error.
 atleast minimum 2gb swap is recommended
