### ISSUE TITLE
On5 ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by vtinoc** [MiCode/patchrom#135]
Device SM-G550T2

Device is stock rom 6.0.1exynos3475 

after running 
../tools/releasetools/ota_target_from_phone -r

I get this error
> Compress the target_files dir into zip file
/home/vtinoc/bin/patchrom/on5
Build full ota package: /home/vtinoc/bin/patchrom/on5/stockrom.zip
unzipping target target-files...
loaded device-specific extensions from /home/vtinoc/bin/patchrom/on5
building image from target_files BOOT...
Traceback (most recent call last):
  File "/home/vtinoc/bin/patchrom/tools/releasetools/ota_from_target_files", line 1792, in <module>
    main(sys.argv[1:])
  File "/home/vtinoc/bin/patchrom/tools/releasetools/ota_from_target_files", line 1747, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/vtinoc/bin/patchrom/tools/releasetools/ota_from_target_files", line 640, in WriteFullOTAPackage
    system_items.GetMetadata(input_zip)
  File "/home/vtinoc/bin/patchrom/tools/releasetools/ota_from_target_files", line 202, in GetMetadata
    key, value = element.split("=")
ValueError: need more than 1 value to unpack

**Comment by WarrenLobo** [comment]
Create fullota manually from target files

**Comment by vtinoc** [comment]
Will try that.
When you say create fullota manually,
Open target folder and make zip?

**Comment by WarrenLobo** [comment]
yep

**Comment by alcarushik** [comment]
Hi. I have same issue after run "make fullota" command. What is wrong?
log
signing: SpacesCore.apk                               (/home/alex/bin/patchrom/build/security/platform)
done.
Build full ota package: /home/alex/bin/patchrom/jagj3ds/out/fullota.zip
unzipping target target-files...
loaded device-specific extensions from /home/alex/bin/patchrom/jagj3ds
Traceback (most recent call last):
  File "/home/alex/bin/patchrom/tools/releasetools/ota_from_target_files", line 1792, in <module>
    main(sys.argv[1:])
  File "/home/alex/bin/patchrom/tools/releasetools/ota_from_target_files", line 1747, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/alex/bin/patchrom/tools/releasetools/ota_from_target_files", line 544, in WriteFullOTAPackage
    device_specific.FullOTA_Assertions()
  File "/home/alex/bin/patchrom/tools/releasetools/common.py", line 1005, in FullOTA_Assertions
    return self._DoCall("FullOTA_Assertions")
  File "/home/alex/bin/patchrom/tools/releasetools/common.py", line 994, in _DoCall
    getattr(self.miui_module, function_name)(*((self,) + args), **kwargs)
  File "/home/alex/bin/patchrom/tools/releasetools/miui_releasetools.py", line 7, in FullOTA_Assertions
    info.script.Mount("/data")
  File "/home/alex/bin/patchrom/tools/releasetools/edify_generator.py", line 188, in Mount
    p.fs_type, common.PARTITION_TYPES[p.fs_type], p.device,
KeyError: 'auto'
/home/alex/bin/patchrom/build/porting.mk:314: ошибка выполнения рецепта для цели «fullota»
make: *** [fullota] Ошибка 1

**Comment by aymende7** [comment]
check filesystem_config.txt in metadata folder

**Comment by alcarushik** [comment]
There is a lot of text, what exactly should I check? It`s my first patchrom, i know a little...

**Comment by aymende7** [comment]
must be like this https://github.com/aymende7/Miui8_S2Plus/blob/master/metadata/filesystem_config.txt

**Comment by alcarushik** [comment]
if not? There is a lot of error`s like (system: stat: can't stat '//system:': No such file or directory stat: can't stat '//system:': No such file or directory stat: can't stat '//system:': No such file or directory selabel=u:/system: capabilities=0x0)

**Comment by aymende7** [comment]
like this? https://github.com/aymende7/XTutorials_Miui8/blob/master/metadata/filesystem_config.txt

**Comment by alcarushik** [comment]
No, as it should be, but with errors like " stat: can't stat", in every line

**Comment by alcarushik** [comment]
Like this
/system: stat: can't stat '//system:': No such file or directory stat: can't stat '//system:': No such file or directory stat: can't stat '//system:': No such file or directory selabel=u:/system: capabilities=0x0
build.prop stat: can't stat '/build.prop': No such file or directory stat: can't stat '/build.prop': No such file or directory stat: can't stat '/build.prop': No such file or directory selabel=u:object_r:system_file:s0 capabilities=0x0
recovery-from-boot.bak stat: can't stat '/recovery-from-boot.bak': No such file or directory stat: can't stat '/recovery-from-boot.bak': No such file or directory stat: can't stat '/recovery-from-boot.bak': No such file or directory selabel=u:object_r:system_file:s0 capabilities=0x0
/system/addon.d: stat: can't stat '//system/addon.d:': No such file or directory stat: can't stat '//system/addon.d:': No such file or directory stat: can't stat '//system/addon.d:': No such file or directory selabel=u:/system/addon.d: capabilities=0x0
50-cm.sh stat: can't stat '/50-cm.sh': No such file or directory stat: can't stat '/50-cm.sh': No such file or directory stat: can't stat '/50-cm.sh': No such file or directory selabel=u:object_r:system_file:s0 capabilities=0x0

**Comment by aymende7** [comment]
you need to the rom again using this command
../tools/releasetools/ota_target_from_phone
enable usb debugger & root pull the rom in normal mode (without reboot to recovery)

**Comment by alcarushik** [comment]
I get target-files without this command, using custom stockrom.zip. Whis that command did not work, many error`s like no rights to download

**Comment by alcarushik** [comment]
Like i say:
../tools/releasetools/ota_target_from_phone -n
Wait for the device to be online...
Copy target file template into current working directory
Warning: the ota package will not contain bootimage!!!
Maybe you forget to pass the ota-package parameter.
Are you sure this is really what you want(yes/no):

**Comment by alcarushik** [comment]
Done. This error again
Compress the target_files dir into zip file
/home/alex/bin/patchrom/jagj3ds
Build full ota package: /home/alex/bin/patchrom/jagj3ds/stockrom.zip
unzipping target target-files...
unable to load device-specific module; assuming none
building image from target_files BOOT...
Traceback (most recent call last):
  File "/home/alex/bin/patchrom/tools/releasetools/ota_from_target_files", line 1792, in <module>
    main(sys.argv[1:])
  File "/home/alex/bin/patchrom/tools/releasetools/ota_from_target_files", line 1747, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/alex/bin/patchrom/tools/releasetools/ota_from_target_files", line 640, in WriteFullOTAPackage
    system_items.GetMetadata(input_zip)
  File "/home/alex/bin/patchrom/tools/releasetools/ota_from_target_files", line 202, in GetMetadata
    key, value = element.split("=")
ValueError: need more than 1 value to unpack

**Comment by alcarushik** [comment]
in Filesystem_config : Please root your device, and try again.
But device is rooted

**Comment by leon83** [comment]
Hi there - i could make a new Issue but in fact that i got the same error - i try to ask some help.
Im on Ubuntu 17.04 and try to port a miui to my device but when i start the command ../tools/releasetools/ota_target_from_phone -r the out folder created but it doesnt zip the folder - my question is why? -> ill tried it with 2 devices (a sony z2 and a samsung galaxy note 4) both devices give me the same error - so i think in my configuration is a  error ? - i searched for weeks for a solution but no way - so thats why are writing here - i can give detailed instructions - but ask if someone can help thanks devs!
