### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by 1982Strand** [MiCode/patchrom#14]
This is my outout in the end of the build process:

unzipping target target-files...
using device-specific extensions in .
using prebuilt boot.img...
Traceback (most recent call last):
  File "/root/patchrom/tools/releasetools/ota_from_target_files", line 846, in <module>
    main(sys.argv[1:])
  File "/root/patchrom/tools/releasetools/ota_from_target_files", line 814, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/root/patchrom/tools/releasetools/ota_from_target_files", line 430, in WriteFullOTAPackage
    if boot_img and not device_specific.WriteRawImage("/boot", "boot.img"):
  File "/root/patchrom/tools/releasetools/common.py", line 687, in WriteRawImage
    return self._DoCall("WriteRawImage")
  File "/root/patchrom/tools/releasetools/common.py", line 655, in _DoCall
    return getattr(self.module, function_name)(_((self,) + args), *_kwargs)
  File "./releasetools.py", line 6, in WriteRawImage
    info.script.Mount("/cust")
  File "/root/patchrom/tools/releasetools/edify_generator.py", line 138, in Mount
    p = fstab[mount_point]
KeyError: '/cust'

What does this mean?? Don't know what to look for here.

**Comment by 1982Strand** [comment]
Solved.

Needed a line in recovery.fstab mentioning a /cust partition.
