### ISSUE TITLE
Help i got error 1 while building full ota

### ISSUE THREAD

**Issue by kensukekita** [MiCode/patchrom#143]
i'm getting error 1 and i dont know why i already modified de rej files

thanks in advance

```
kensuke@kensuke-Lenovo-G50-80:~/bin$ sudo make fullota
To add prebuilt files
To add preintall files
Add miui prebuilt completed!
>>> build out/framework.jar...
/home/kensuke/bin//tools/add_miui_smail.sh /home/kensuke/bin//android/base-framework/framework.jar.out out/framework_miui out/framework
Add field TRANSACTION_setCurFocusedWindow:I into out/framework/smali/com/android/internal/view/IInputMethodManager$Stub.smali
Add method setCurFocusedWindow(Landroid/os/IBinder;)V into out/framework/smali/com/android/internal/view/IInputMethodManager$Stub$Proxy.smali
Add method setCurFocusedWindow(Landroid/os/IBinder;)V into out/framework/smali/com/android/internal/view/IInputMethodManager.smali
Add method nativeUnmountStorageOnInit()V into out/framework/smali/com/android/internal/os/Zygote.smali
Add method dexopt(Ljava/lang/String;IZLjava/lang/String;IZ)I into out/framework/smali/com/android/internal/os/InstallerConnection.smali
Add method dexopt(Ljava/lang/String;IZLjava/lang/String;IZI)I into out/framework/smali/com/android/internal/os/InstallerConnection.smali
Add method dexopt(Ljava/lang/String;IZLjava/lang/String;Ljava/lang/String;IZZLjava/lang/String;Z)I into out/framework/smali/com/android/internal/os/InstallerConnection.smali
Add method dexopt(Ljava/lang/String;IZLjava/lang/String;Ljava/lang/String;IZZLjava/lang/String;ZI)I into out/framework/smali/com/android/internal/os/InstallerConnection.smali
Add method removeFileForLowMem()V into out/framework/smali/com/android/internal/os/RuntimeInit.smali
Add field TRANSACTION_OnDoubleClickHome:I into out/framework/smali/com/android/internal/policy/IKeyguardService$Stub.smali
Add method OnDoubleClickHome()V into out/framework/smali/com/android/internal/policy/IKeyguardService$Stub$Proxy.smali
Add method OnDoubleClickHome()V into out/framework/smali/com/android/internal/policy/IKeyguardService.smali
Add method getMiuiTelephony()Lmiui/telephony/IMiuiTelephony; into out/framework/smali/com/android/internal/telephony/ITelephonyRegistry$Stub$Proxy.smali
Add method setMiuiTelephony(Lmiui/telephony/IMiuiTelephony;)V into out/framework/smali/com/android/internal/telephony/ITelephonyRegistry$Stub$Proxy.smali
Add field TRANSACTION_getMiuiTelephony:I into out/framework/smali/com/android/internal/telephony/ITelephonyRegistry$Stub.smali
Add field TRANSACTION_setMiuiTelephony:I into out/framework/smali/com/android/internal/telephony/ITelephonyRegistry$Stub.smali
Add field ACTION_SIM_HOT_SWAP:Ljava/lang/String; into out/framework/smali/com/android/internal/telephony/TelephonyIntents.smali
Add field EXTRA_IS_SIM_ADDED:Ljava/lang/String; into out/framework/smali/com/android/internal/telephony/TelephonyIntents.smali
Add method getMiuiTelephony()Lmiui/telephony/IMiuiTelephony; into out/framework/smali/com/android/internal/telephony/ITelephonyRegistry.smali
Add method setMiuiTelephony(Lmiui/telephony/IMiuiTelephony;)V into out/framework/smali/com/android/internal/telephony/ITelephonyRegistry.smali
Add field TRANSACTION_setStatus:I into out/framework/smali/com/android/internal/statusbar/IStatusBarService$Stub.smali
Add method setStatus(ILjava/lang/String;Landroid/os/Bundle;)V into out/framework/smali/com/android/internal/statusbar/IStatusBar$Stub$Proxy.smali
Add method setStatus(ILandroid/os/IBinder;Ljava/lang/String;Landroid/os/Bundle;)V into out/framework/smali/com/android/internal/statusbar/IStatusBarService$Stub$Proxy.smali
Add field TRANSACTION_setStatus:I into out/framework/smali/com/android/internal/statusbar/IStatusBar$Stub.smali
Add method setStatus(ILjava/lang/String;Landroid/os/Bundle;)V into out/framework/smali/com/android/internal/statusbar/IStatusBar.smali
Add method setStatus(ILandroid/os/IBinder;Ljava/lang/String;Landroid/os/Bundle;)V into out/framework/smali/com/android/internal/statusbar/IStatusBarService.smali
Add method destroy()V into out/framework/smali/com/android/internal/app/ChooserActivity$ChooserTargetServiceConnection.smali
Add method addResolverSettings()V into out/framework/smali/com/android/internal/app/ResolverActivity$ResolveListAdapter.smali
Add field mChooserActivity:Lcom/android/internal/app/ChooserActivity; into out/framework/smali/com/android/internal/app/ChooserActivity$ChooserTargetServiceConnection.smali
Add field mConnectedComponent:Landroid/content/ComponentName; into out/framework/smali/com/android/internal/app/ChooserActivity$ChooserTargetServiceConnection.smali
Add field mLock:Ljava/lang/Object; into out/framework/smali/com/android/internal/app/ChooserActivity$ChooserTargetServiceConnection.smali
Add method reorderList()V into out/framework/smali/com/android/internal/app/ResolverActivity$ResolveListAdapter.smali
Add method <init>(Lcom/android/internal/app/ResolverActivity;Landroid/widget/BaseAdapter;Lcom/android/internal/app/ResolverActivity$DisplayResolveInfo;)V into out/framework/smali/com/android/internal/app/ResolverActivity$LoadAdapterIconTask.smali
Add field adapter:Landroid/widget/BaseAdapter; into out/framework/smali/com/android/internal/app/ResolverActivity$LoadAdapterIconTask.smali
Add method checkOperationInternal(IILjava/lang/String;)I into out/framework/smali/com/android/internal/app/IAppOpsService.smali
Add method isControlAllowed(ILjava/lang/String;)Z into out/framework/smali/com/android/internal/app/IAppOpsService.smali
Add method registerCallback(Lcom/android/internal/app/IOpsCallback;)I into out/framework/smali/com/android/internal/app/IAppOpsService.smali
Add method checkOperationInternal(IILjava/lang/String;)I into out/framework/smali/com/android/internal/app/IAppOpsService$Stub$Proxy.smali
Add method isControlAllowed(ILjava/lang/String;)Z into out/framework/smali/com/android/internal/app/IAppOpsService$Stub$Proxy.smali
Add method registerCallback(Lcom/android/internal/app/IOpsCallback;)I into out/framework/smali/com/android/internal/app/IAppOpsService$Stub$Proxy.smali
Add method inflateGridView(I)Landroid/widget/GridView; into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add method initGridViews()V into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add field TRANSACTION_checkOperationInternal:I into out/framework/smali/com/android/internal/app/IAppOpsService$Stub.smali
Add field TRANSACTION_isControlAllowed:I into out/framework/smali/com/android/internal/app/IAppOpsService$Stub.smali
Add method finish()V into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add field TRANSACTION_registerCallback:I into out/framework/smali/com/android/internal/app/IAppOpsService$Stub.smali
Add method <init>(Lcom/android/internal/app/ResolverActivity;I)V into out/framework/smali/com/android/internal/app/ResolverActivity$ItemClickListener.smali
Add method onPrepareAdapterView(Lcom/android/internal/app/ResolverActivity$ResolveListAdapter;Z)V into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add field start:I into out/framework/smali/com/android/internal/app/ResolverActivity$ItemClickListener.smali
Add field EXTRA_RESOLVE_INFOS:Ljava/lang/String; into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add field MAX_PER_SCREEN:I into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add field mComponentOrders:Ljava/util/List; into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add field mIconSize:I into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add method onPrepareAdapterView(Lcom/android/internal/app/ResolverActivity$ResolveListAdapter;Z)V into out/framework/smali/com/android/internal/app/ChooserActivity.smali
Add field mMaskColor:I into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add field mScreenView:Lmiui/widget/ScreenView; into out/framework/smali/com/android/internal/app/ResolverActivity.smali
Add field extraFlags:I into out/framework/smali/android/view/WindowManager$LayoutParams.smali
Add method isEdgeTouchEvent()Z into out/framework/smali/android/view/MotionEvent.smali
Add method notifyBackLidSwitchChanged(JZ)V into out/framework/smali/android/view/WindowManagerPolicy.smali
Add method screenshot(II)Landroid/graphics/Bitmap; into out/framework/smali/android/view/Surface.smali
Add field TOOL_TYPE_EDGE_TOUCH:I into out/framework/smali/android/view/MotionEvent.smali
Add method setFocusedWindow(Landroid/view/View;)V into out/framework/smali/android/view/inputmethod/InputMethodManager.smali
Add method addExtraFlags(I)V into out/framework/smali/android/view/Window.smali
Add field DISPATCH_NO_METHOD:I into out/framework/smali/android/view/inputmethod/InputMethodManager.smali
Add method clearExtraFlags(I)V into out/framework/smali/android/view/Window.smali
Add method setExtraFlags(II)V into out/framework/smali/android/view/Window.smali
Add method nInitialize(JLandroid/view/Surface;)V into out/framework/smali/android/view/ThreadedRenderer.smali
Add method setBlur(Z)V into out/framework/smali/android/view/SurfaceControl.smali
Add field FLAG_BLUR:I into out/framework/smali/android/view/SurfaceControl.smali
Add method setType(I)V into out/framework/smali/android/widget/Toast.smali
Add method dismiss()V into out/framework/smali/android/widget/Editor$PinnedPopupWindow.smali
Add method continueWhenFinished(Z)Z into out/framework/smali/android/widget/OverScroller$SplineOverScroller.smali
Add method setDecelerationScale(F)V into out/framework/smali/android/widget/OverScroller$SplineOverScroller.smali
Add method setTotalOverDistance(I)V into out/framework/smali/android/widget/OverScroller$SplineOverScroller.smali
Add method update(Z)Z into out/framework/smali/android/widget/OverScroller$SplineOverScroller.smali
Add field mDecelerationScale:F into out/framework/smali/android/widget/OverScroller$SplineOverScroller.smali
Add field mTotalOverDistance:I into out/framework/smali/android/widget/OverScroller$SplineOverScroller.smali
Add method clipVertically(I)I into out/framework/smali/android/widget/Editor$HandleView.smali
Add method getHandleExtension(I)I into out/framework/smali/android/widget/Editor$HandleView.smali
Add method getActionPopupWindow()Landroid/widget/Editor$ActionPopupWindow; into out/framework/smali/android/widget/Editor$HandleView.smali
Add field isEnabled:Z into out/framework/smali/android/widget/AbsListView$LayoutParams.smali
Add method hideActionPopupWindow()V into out/framework/smali/android/widget/Editor$HandleView.smali
Add method isPopshowing()Z into out/framework/smali/android/widget/Editor$HandleView.smali
Add method onAttached()V into out/framework/smali/android/widget/Editor$HandleView.smali
Add method showActionPopupWindow(I)V into out/framework/smali/android/widget/Editor$HandleView.smali
Add field mActionPopupShower:Ljava/lang/Runnable; into out/framework/smali/android/widget/Editor$HandleView.smali
Add field mActionPopupWindow:Landroid/widget/Editor$ActionPopupWindow; into out/framework/smali/android/widget/Editor$HandleView.smali
Add field mAnimationFadeIn:Landroid/animation/AnimatorSet; into out/framework/smali/android/widget/Editor$HandleView.smali
Add field mAnimationFadeOut:Landroid/animation/AnimatorSet; into out/framework/smali/android/widget/Editor$HandleView.smali
Add field mAnimationFadeOutListener:Landroid/animation/AnimatorListenerAdapter; into out/framework/smali/android/widget/Editor$HandleView.smali
Add field mContainer:Landroid/widget/Editor$AnimatePopupWindow; into out/framework/smali/android/widget/Editor$HandleView.smali
Add field mHandleExtension:I into out/framework/smali/android/widget/Editor$HandleView.smali
Add field mHorizontalScale:F into out/framework/smali/android/widget/Editor$HandleView.smali
Add method canSelectText()Z into out/framework/smali/android/widget/Editor.smali
Add field mLastWindowY:I into out/framework/smali/android/widget/Editor$HandleView.smali
Add method getCharRange(I)J into out/framework/smali/android/widget/Editor.smali
Add method getDescendantViewScale(Landroid/view/View;)F into out/framework/smali/android/widget/Editor.smali
Add method getPrimaryHorizontal(Landroid/text/Layout;Landroid/text/Layout;IZ)F into out/framework/smali/android/widget/Editor.smali
Add method hasPasswordTransformationMethod()Z into out/framework/smali/android/widget/Editor.smali
Add method isPositionVisible(II)Z into out/framework/smali/android/widget/Editor.smali
Add method setSelectionTranslation(II)V into out/framework/smali/android/widget/Editor.smali
Add method areSuggestionsShown()Z into out/framework/smali/android/widget/Editor.smali
Add method isInSwipeSelectionMode()Z into out/framework/smali/android/widget/Editor.smali
Add method stopSelectionActionMode()V into out/framework/smali/android/widget/Editor.smali
Add field mMockActionMode:Landroid/view/ActionMode; into out/framework/smali/android/widget/Editor.smali
Add field mIsUsingMiui:Z into out/framework/smali/android/widget/EdgeEffect.smali
Add field mFirstTouchUp:Z into out/framework/smali/android/widget/Editor.smali
Add method requestDisallowInterceptTouchEvent(Z)V into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add method setMaxTouchOffset(I)V into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add method setMinTouchOffset(I)V into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add method setTranslationCache([F)V into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add field DELAY_BEFORE_REPLACE_ACTION:I into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add field mDoubleTabed:Z into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add field mInSwipeSelectionMode:Z into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add field mPreviousTapUpTime:J into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add field mSwipeSelectionStart:I into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add field mTextSelectionModeEnable:Z into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add field mTranslationCache:[F into out/framework/smali/android/widget/Editor$SelectionModifierCursorController.smali
Add method createAnimations()V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method cancelAnimations()V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method fadeIn(II)V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method fadeOut()V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method hide()V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method onAttached()V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method onMeasure(II)V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method setY(I)V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method showWithActionPopup()V into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add field mReShowPopup:Z into out/framework/smali/android/widget/Editor$InsertionHandleView.smali
Add method checkSpringBackState()Z into out/framework/smali/android/widget/OverScroller.smali
Add method getCurrYVelocity()F into out/framework/smali/android/widget/OverScroller.smali
Add method setDecelerationScale(F)V into out/framework/smali/android/widget/OverScroller.smali
Add method setSpringOverScrollEnable(Z)V into out/framework/smali/android/widget/OverScroller.smali
Add method setTotalOverDistance(I)V into out/framework/smali/android/widget/OverScroller.smali
Add field mSpringOverScrollEnable:Z into out/framework/smali/android/widget/OverScroller.smali
Add method getVerticalSpacing()I into out/framework/smali/android/widget/AbsListView.smali
Add method showWithActionPopup()V into out/framework/smali/android/widget/Editor$InsertionPointCursorController.smali
Add field mHapticEnabledExplicitly:Z into out/framework/smali/android/view/View.smali
Add field BOUNCE_BACK_TIME:I into out/framework/smali/android/widget/AbsListView.smali
Add field BOUNCE_DECAY:F into out/framework/smali/android/widget/AbsListView.smali
Add field BOUNCE_FORWARD_TIME:I into out/framework/smali/android/widget/AbsListView.smali
Add field BOUNCE_MULTIPLY:I into out/framework/smali/android/widget/AbsListView.smali
Add field mCursorRectInWindow:Landroid/graphics/Rect; into out/framework/smali/android/widget/Editor$InputMethodState.smali
Add field mTmpOffset:[F into out/framework/smali/android/widget/Editor$InputMethodState.smali
Add field mTmpRectF:Landroid/graphics/RectF; into out/framework/smali/android/widget/Editor$InputMethodState.smali
Add field TRANSFORM_DELAY:I into out/framework/smali/android/widget/AbsListView.smali
Add field mAnimatorSet:Landroid/animation/AnimatorSet; into out/framework/smali/android/widget/AbsListView.smali
Add field mDownMotionY:I into out/framework/smali/android/widget/AbsListView.smali
Add field mInertia:I into out/framework/smali/android/widget/AbsListView.smali
Add field mIsShortList:Z into out/framework/smali/android/widget/AbsListView.smali
Add field mIsTouching:Z into out/framework/smali/android/widget/AbsListView.smali
Add field mLastPivotX:F into out/framework/smali/android/widget/AbsListView.smali
Add field mLastPivotY:F into out/framework/smali/android/widget/AbsListView.smali
Add field mOffsetRevise:I into out/framework/smali/android/widget/AbsListView.smali
Add field mScaleY:F into out/framework/smali/android/widget/AbsListView.smali
Add field mScaleYDirty:Z into out/framework/smali/android/widget/AbsListView.smali
Add method setCursorDrawableRes(I)V into out/framework/smali/android/widget/TextView.smali
/home/kensuke/bin//tools/apktool --quiet b out/framework -o out/framework.jar
out/framework/smali/android/app/ResourcesManager.smali[1156,4] There is already a label with that name.
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: android/app/ResourcesManager.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:67)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:51)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:364)
	at brut.androlib.Androlib.buildSources(Androlib.java:295)
	at brut.androlib.Androlib.build(Androlib.java:278)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
make: *** [out/framework.jar] Error 1
kensuke@kensuke-Lenovo-G50-80:~/bin$ 


```

**Comment by kensukekita** [comment]
i changed apktool files and now i'm getting this error :P 
```
/home/kensuke/bin//tools/apktool --quiet b out/framework -o out/framework.jar
Exception in thread "main" Can't construct a java object for tag:yaml.org,2002:brut.androlib.meta.MetaInfo; exception=Class not found: brut.androlib.meta.MetaInfo
 in 'reader', line 1, column 1:
    !!brut.androlib.meta.MetaInfo
    ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:333)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:249)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: org.yaml.snakeyaml.error.YAMLException: Class not found: brut.androlib.meta.MetaInfo
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:633)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:321)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
	... 10 more
make: *** [out/framework.jar] Error 1

```
