### ISSUE TITLE
Error: tools/releasetools/ota_from_target_files

### ISSUE THREAD

**Issue by FFY00** [MiCode/patchrom#153]
```
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
using prebuilt boot.img...
Traceback (most recent call last):
  File "/home/anubis/git/miui_baffinlite/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/anubis/git/miui_baffinlite/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/anubis/git/miui_baffinlite/patchrom/tools/releasetools/ota_from_target_files", line 432, in WriteFullOTAPackage
    Item.GetMetadata(input_zip)
  File "/home/anubis/git/miui_baffinlite/patchrom/tools/releasetools/ota_from_target_files", line 163, in GetMetadata
    name, uid, gid, mode = columns[:4]
ValueError: need more than 2 values to unpack
```

**Comment by leon83** [comment]
Got the same error too - i have posted this in the miui forum and the mod want to help but than i was in hospital and till now no answer cause think hes busy but when i got an answer i post to help - the only thing i can tell it has something to do with the files in metadata folder - especially with recovery.fstab - so the mod tell me hope you understand . greets
