### ISSUE TITLE
firstpatch issue

### ISSUE THREAD

**Issue by FFY00** [MiCode/patchrom#154]
When running `firstpatch`.
```
patch: **** Can't reopen file PATH/patchrom/baffinlite/android.policy.jar.out/./smali/com/android/internal/policy/impl/PhoneWindowManager.smali : No such file or directory
```
This is happening to all files. No files are written to `reject`.

**Comment by leon83** [comment]
How do you fix the error with the ota_from_target_files ? im stuck at these sadly ...
thank you

**Comment by FFY00** [comment]
Post the log.

**Comment by leon83** [comment]
Hi and thanks a lot for reply for short:
Recovery link files success
rm: can't remove '/system/xbin/getfilesysteminfo': No such file or directory
Build apkcerts.txt
6054 KB/s (1612268 bytes in 0.260s)
Generate metadata used to build target files...
Decode oat files
Compress the target_files dir into zip file
/home/lwx/bin/patchrom/device
Build full ota package: /home/lwx/bin/patchrom/device/stockrom.zip
unzipping target target-files...
loaded device-specific extensions from /home/lwx/bin/patchrom/device
using prebuilt boot.img from BOOTABLE_IMAGES...
Traceback (most recent call last):
  File "/home/lwx/bin/patchrom/tools/releasetools/ota_from_target_files", line 1792, in <module>
    main(sys.argv[1:])
  File "/home/lwx/bin/patchrom/tools/releasetools/ota_from_target_files", line 1747, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/lwx/bin/patchrom/tools/releasetools/ota_from_target_files", line 640, in WriteFullOTAPackage
    system_items.GetMetadata(input_zip)
  File "/home/lwx/bin/patchrom/tools/releasetools/ota_from_target_files", line 202, in GetMetadata
    key, value = element.split("=")
ValueError: need more than 1 value to unpack

i uploaded the full console output here 
part1: http://pasted.co/61aebe5c
part2: http://pasted.co/55a375b9

if you need further details let me know :) greets

**Comment by leon83** [comment]
hmm sad but anyway thx  think youre busy :(

**Comment by FFY00** [comment]
Yeah, sorry for that. It seems that the script is outdated for you device's file structure. You can try to fix it if you have time.
