### ISSUE TITLE
Problem(

### ISSUE THREAD

**Issue by axel2033** [MiCode/patchrom#2]
/home/ilia/android/miui/tools/remove_redef.py >/dev/null out/framework-res
/home/ilia/android/miui/tools/apktool --quiet b out/framework-res out/framework-res.apk
/home/ilia/android/miui/tools/apktool --quiet if out/framework-res.apk
<<< build out/framework-res.apk completed!

> > > build out/framework-miui-res.apk...
> > > /home/ilia/android/miui/tools/apktool --quiet d -f /home/ilia/android/miui/miui/system/framework/framework-miui-res.apk out/framework-miui-res
> > > ls: невозможно получить доступ к overlay/framework-miui-res/res/[^v]_: Нет такого файла или каталога
> > > /home/ilia/android/miui/tools/apktool --quiet b out/framework-miui-res out/framework-miui-res.apk
> > > Exception in thread "main" brut.androlib.err.CantFindFrameworkResException
> > >     at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:366)
> > >     at brut.androlib.Androlib.parseUsesFramework(Androlib.java:400)
> > >     at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
> > >     at brut.androlib.Androlib.buildResources(Androlib.java:248)
> > >     at brut.androlib.Androlib.build(Androlib.java:171)
> > >     at brut.androlib.Androlib.build(Androlib.java:154)
> > >     at brut.apktool.Main.cmdBuild(Main.java:182)
> > >     at brut.apktool.Main.main(Main.java:67)
> > > make: *_\* [out/framework-miui-res.apk] Ошибка 1

In what can be problem?

**Comment by MiuiAnderson** [comment]
Can you tell me which command you run for make?

**Comment by axel2033** [comment]
make fullota
I tried to do it for p990 bases on cm9

**Comment by MiuiAnderson** [comment]
We required that the base ROM is at least android 4.0 version. Otherwise, the framework-miui-res.apk can't be built.

---

发件人: Ilia Aksyonov [reply@reply.github.com]
发送时间: 2012年3月16日 19:40
到: 汪文俊
主题: Re: [patchrom] Problem( (#2)

make fullota
I tried to do it for p990 bases on cm9

---

**Comment by axel2033** [comment]
sad :-(
Will be optimus 2x officialy supported by hiaomi and other miui dev team?(Miuiv4)

**Comment by MiuiAnderson** [comment]
The pricinple is that the device manufacturer released the stock 4.0 ROM, we will port miui to it. And you can .

---

发件人: Ilia Aksyonov [reply@reply.github.com]
发送时间: 2012年3月16日 20:05
到: 汪文俊
主题: Re: [patchrom] Problem( (#2)

sad :-(
Will be optimus 2x officialy supported by hiaomi and other miui dev team?(Miuiv4)

---

**Comment by axel2033** [comment]
New Miuiv4 bases on stock firmware?
In the last year miui bases on cyanogenmod sources.
I'm right?

**Comment by MiuiAnderson** [comment]
Yes, the miui 2.3 is based on cm. But from 4.0, we only based on stock firmware. That's why we create patchrom
project.

---

发件人: Ilia Aksyonov [reply@reply.github.com]
发送时间: 2012年3月16日 20:25
到: 汪文俊
主题: Re: [patchrom] Problem( (#2)

New Miuiv4 bases on stock firmware?
In the last year miui bases on cyanogenmod sources.
I'm right?

---

**Comment by axel2033** [comment]
Sorry, you can ask a question?
Why did you decide to go this route?
Cyanogenmod a great project and I think it was good base for miui 2.3.
Why you started to change stock roms intead of building firmware from source?

**Comment by MiuiAnderson** [comment]
Yes, cm is indeed a great project.

But we think the stock firmware is more stable, in miui 2.3, many users complain wifi, power saving and phone call

issues. And we nearly can't have a good way to solve it. 

---

发件人: Ilia Aksyonov [reply@reply.github.com]
发送时间: 2012年3月16日 20:43
到: 汪文俊
主题: Re: [patchrom] Problem( (#2)

Sorry, you can ask a question?
Why did you decide to go this route?
Cyanogenmod a great project and I think it was good base for miui 2.3.
Why you started to change stock roms intead of building firmware from source?

---

**Comment by adyscorpius** [comment]
I got a similar error Andy. 

/adit/android/patchrom/tools/apktool --quiet d -f /adit/android/patchrom/miui/system/framework/framework-miui-res.apk out/framework-miui-res
ls: cannot access overlay/framework-miui-res/res/[^v]_: No such file or directory
ls: cannot access overlay/framework-miui-res/res/values_: No such file or directory
/adit/android/patchrom/tools/apktool --quiet b out/framework-miui-res out/framework-miui-res.apk
Exception in thread "main" brut.androlib.err.CantFindFrameworkResException
    at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:366)
    at brut.androlib.Androlib.parseUsesFramework(Androlib.java:400)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
    at brut.androlib.Androlib.buildResources(Androlib.java:248)
    at brut.androlib.Androlib.build(Androlib.java:171)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
make: **\* [out/framework-miui-res.apk] Error 1

I'm using 4.0.4 base. Also have the latest android-sdk-linux updated on Ubuntu 64 Bit. Could you help with where I'm going wrong?

**Comment by 1982Strand** [comment]
About the Exception in thread "main" brut.androlib.err.CantFindFrameworkResException -error. Remember to manually  install a framework with id 2, like a sense framework. If you run as root it should be in /root/apktool - otherwise /home/(user)/apktool

**Comment by jcorrea86** [comment]
Sorry for the noob question, but how would I manually install a framework with id 2?  I'm trying to port MIUI to the bionic

**Comment by 1982Strand** [comment]
i use com.htc.resources.apk as the no.2 framework. You install it manually with following command:
apktool if com.htc.resources.apk

then it automatically installs as 2.apk ;)

**Comment by jcorrea86** [comment]
Thanks for the help, but when I run the command above, it saves the framework as id3 instead of 2.  If I go to /home/apktool i only see 1.apk and 3.apk

**Comment by 1982Strand** [comment]
yes, the framework-res.apk installs as 1.apk, framework-miui-res.apk installs as 3.apk. You need to find a framework that installs as 2. In my case, com.htc.resources.apk installs as 2.apk. Find a sense rom with the com.htc.resources.apk in it, it will install as 2.apk ;)

**Comment by jcorrea86** [comment]
got it... Now i just need to find which apk would be the 2.apk for a motorola phone.... Thanks!

**Comment by 1982Strand** [comment]
Use this:

http://htcfanboys.com/download/1982Strand/?action=view&file=4490

**Comment by jcorrea86** [comment]
I found the framework that gave me id 2, but it still fails and now gives me a lot of errors.  If I run apktool (apktool b out/framework-miui-res.apk) manually, it starts with:

W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...

and then a lot of:

/home/jr/stspatchrom/aosp/out/framework-miui-res/res/values/styles.xml:327: error: Error: No resource found that matches the given name: attr 'background'.
/home/jr/stspatchrom/aosp/out/framework-miui-res/res/values/styles.xml:328: error: Error: No resource found that matches the given name: attr 'clickable'.
/home/jr/stspatchrom/aosp/out/framework-miui-res/res/values/styles.xml:330: error: Error: No resource found that matches the given name: attr 'cropToPadding'.
/home/jr/stspatchrom/aosp/out/framework-miui-res/res/values/styles.xml:329: error: Error: No resource found that matches the given name: attr 'scaleType'.
/home/jr/stspatchrom/aosp/out/framework-miui-res/res/values/styles.xml:331: error: Error: No resource found that matches the given name: attr 'src'.
/home/jr/stspatchrom/aosp/out/framework-miui-res/res/values/styles.xml:334: error: Error: No resource found that matches the given name: attr 'itemTextAppearance'.
/home/jr/stspatchrom/aosp/out/framework-miui-res/res/values/styles.xml:335: error: Error: No resource found that matches the given name: attr 'listViewStyle'.
/home/jr/stspatchrom/aosp/out/framework-miui-res/res/values/styles.xml:336: error: Error: No resource found that matches the given name: attr 'windowAnimationStyle'.

**Comment by 1982Strand** [comment]
Delete contents of the folder "out", do a repo sync if not already done and re-run the build process :)

**Comment by jcorrea86** [comment]
unfortunately I get the same error as above.

**Comment by 1982Strand** [comment]
Hmm, not sure what's going on then, can't help you, sorry.

**Comment by iBotPeaches** [comment]
Run

cd /home/jr/stspatchrom/
apktool if com.htc.resources.apk
source build/envsetup.sh
cd aosp (or name of folder where your doing it)
make reallyclean
make fullota

Run those in order from top to bottom. Starting in the root directory of patchrom.

**Comment by jcorrea86** [comment]
THANK YOU THANK YOU THANK YOU THANK YOU!!!! 

That worked for me!  I am now one step close to building a port for the bionic!

**Comment by adyscorpius** [comment]
Hey, i'm using CM9 as base. Which also means there isn't a second stock framework to load. How should I go about this? Which apk should I install as 2.apk? Thanks!!!

**Comment by ingbrzy** [comment]
@Adyscorpius

use this
http://uloz.to/x3bEPSt/twframework-res-apk
http://uloz.to/xo1kmhS/2-apk
