### ISSUE TITLE
Pulling from recovery

### ISSUE THREAD

**Issue by jcorrea86** [MiCode/patchrom#27]
I am trying to pull from a leak of ICS for the bionic and I got this error below.  Any help would be most appreciated.

Compress the target_files dir into zip file
/home/junior/stspatchrom/bio
Build full ota package: /home/junior/stspatchrom/bio/stockrom.zip
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
Traceback (most recent call last):
  File "/home/junior/stspatchrom/tools/releasetools/ota_from_target_files", line 846, in <module>
    main(sys.argv[1:])
  File "/home/junior/stspatchrom/tools/releasetools/ota_from_target_files", line 814, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/junior/stspatchrom/tools/releasetools/ota_from_target_files", line 398, in WriteFullOTAPackage
    script.FormatPartition("/system")
  File "/home/junior/stspatchrom/tools/releasetools/edify_generator.py", line 172, in FormatPartition
    (p.fs_type, common.PARTITION_TYPES[p.fs_type],
KeyError: 'auto'

**Comment by 1982Strand** [comment]
Not entirely sure about this, but got an idea what it might be. The partition type "auto"  isnt recognised or found, check your metadata and look at the recovery.fstab file in patchrom. If the partition type "auto" isnt on the list you need to add it, if it is, try simply removing it..

**Comment by jcorrea86** [comment]
I added the auto partition type to the fstab but I still get the error.  I compated the fstab that was pulled to the one that is in patchrom and made a few changes, but it still has the same error

**Comment by jcorrea86** [comment]
I think I fixed it... I added the Auto in the recovery.fstab and I added it to the common.py files and it worked, except for a new error:

Compress the target_files dir into zip file
/home/junior/stspatchrom/bio
Build full ota package: /home/junior/stspatchrom/bio/stockrom.zip
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2798)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:111)
    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:178)
    at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:135)
    at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:289)
    at com.android.signapk.SignApk.copyFiles(SignApk.java:422)
    at com.android.signapk.SignApk.main(SignApk.java:490)

   ERROR: signapk.jar failed: return code 1

junior@junior-aspire:~/stspatchrom/bio$

**Comment by iBotPeaches** [comment]
^ need moar memory.

**Comment by jcorrea86** [comment]
I found online that the error is caused by Java running out of memory and I found that I needed to change "java", "-Xmx1024m", "-jar" in Common.py

I changed it to Xmx512m which should have solved this, but it is still giving me this error.  I have 3gb of ram and about 50gb of HDD space, so is it still a memory issue?  What else can I do?

**Comment by MasterZen88** [comment]
Try 

java -Xms1024m -Xmx1024m

**Comment by jcorrea86** [comment]
got it working now...
