### ISSUE TITLE
Service.Jar - Could not smali file:

### ISSUE THREAD

**Issue by MasterZen88** [MiCode/patchrom#28]
/home/jared/Android/patchrom/tools/apktool --quiet b out/services out/services.jar
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: java.io.FileInputStream@8afcd0c
    at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
    at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
    at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:64)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:48)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:222)
    at brut.androlib.Androlib.buildSources(Androlib.java:179)
    at brut.androlib.Androlib.build(Androlib.java:170)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
make: **\* [out/services.jar] Error 1
jared@ubuntu:~/Android/patchrom/d710$ ../tools/smali services.jar.out
jared@ubuntu:~/Android/patchrom/d710$ 

Any help would be greatly appreciated!

**Comment by MasterZen88** [comment]
Just wanted to add I did fix all reject related to services.jar

**Comment by 1982Strand** [comment]
Think you messed up one or more of your patches then. Try to recompile your services.jar just with smali.jar and not apktool. It will show you more Info on the error..

**Comment by MasterZen88** [comment]
Kinda odd it did not show any error's. However when I first ran smali on sevices.jar it had some error which I fixed. Then I recompiled and had the above problem. Also thanks for your help!

jared@ubuntu:~/Android/patchrom/d710$ ../tools/smali services.jar.out
jared@ubuntu:~/Android/patchrom/d710$

**Comment by jcorrea86** [comment]
don't forget to delete the file from the out folder and then run it again.  I would have this issue from to time, but if I delete the folder and file in the OUT folder, it runs fine afterwards.

**Comment by fanoge** [comment]
suggest to use smali to locate where the error comes from:
smali out/services

thanks.

**Comment by MasterZen88** [comment]
Thanks for the advice jcorrea86, that pointed me to a new error which I was able to fix. Now it looks like I have a new problem with framework-res

Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL6649506695478758490.tmp, -x, -S, /home/jared/Android/patchrom/epic4gtouch/out/framework-res/res, -M, /home/jared/Android/patchrom/epic4gtouch/out/framework-res/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
    at brut.androlib.Androlib.buildResources(Androlib.java:248)
    at brut.androlib.Androlib.build(Androlib.java:171)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL6649506695478758490.tmp, -x, -S, /home/jared/Android/patchrom/epic4gtouch/out/framework-res/res, -M, /home/jared/Android/patchrom/epic4gtouch/out/framework-res/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:83)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
    ... 6 more
make: **\* [out/framework-res.apk] Error 1

**Comment by MasterZen88** [comment]
Here is the complete error:

/home/jared/Android/patchrom/tools/remove_redef.py >/dev/null out/framework-res
/home/jared/Android/patchrom/tools/apktool --quiet b out/framework-res out/framework-res.apk
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/layout-w600dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-sw600dp-land
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-w500dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-sw600dp-w1280dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-w720dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-w600dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-sw600dp-w1024dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-w360dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/drawable-sw600dp-hdpi
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-w480dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-h720dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/layout-sw600dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-sw600dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/layout-sw400dp
invalid resource directory name: /home/jared/Android/patchrom/epictouch/out/framework-res/res/values-sw400dp
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL1320644528220111825.tmp, -x, -S, /home/jared/Android/patchrom/epictouch/out/framework-res/res, -M, /home/jared/Android/patchrom/epictouch/out/framework-res/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
    at brut.androlib.Androlib.buildResources(Androlib.java:248)
    at brut.androlib.Androlib.build(Androlib.java:171)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL1320644528220111825.tmp, -x, -S, /home/jared/Android/patchrom/epictouch/out/framework-res/res, -M, /home/jared/Android/patchrom/epictouch/out/framework-res/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:83)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
    ... 6 more
make: **\* [out/framework-res.apk] Error 1
jared@ubuntu:~/Android/patchrom/epictouch$ 

Also I'm building for a Samsung Epic 4G Touch

**Comment by MasterZen88** [comment]
Well looks like Im getting closer. After removing all invalid resources I'm am left with some un-defined public symbols. Guess I'll have to clean that up. Does anyone know a better whay to clean the public.xml file?

**Comment by MasterZen88** [comment]
OKay  looks like the rom zip. But now when I try to compile Micode for another device I get the below message:

jared@ubuntu:~/Android/patchrom/wsg$ make workspace
/home/jared/Android/patchrom/build/util.mk:177: **\* multiple target patterns.  Stop.

Anyone know anything about this. Been working at it for the last two hours.

**Comment by jcorrea86** [comment]
I have never seen that one, but I did see this:

http://stackoverflow.com/questions/2100448/multiple-target-patterns-makefile-error

Maybe it can help

**Comment by fanoge** [comment]
well, I have added a new target for local ota purpose and line 177 of util.mk is that target.
Could you "make verify" to check the value of OTA_BASE to see if anything is wrong?

**Comment by MasterZen88** [comment]
KInda odd.... so I had created a folder name d710, compiled my new miui rom then after testing I wanted to wipe the files in-side and start from scratch but use the same folder name. When I attempt this process it gave me error:

jared@ubuntu:~/Android/patchrom/wsg$ make workspace
/home/jared/Android/patchrom/build/util.mk:177: **\* multiple target patterns. Stop.

But if I create a whole new folder called epictouch then try the same process every work's out fine. So I guess the ??? is when you run make workspace does it save to a cache location or reports the folder its currently working in... Something must not be getting cleaned.

**Comment by fanoge** [comment]
Looks like something wrong with the internal variable 'OTA_BASE' and you could check it with "make verify"

**Comment by MasterZen88** [comment]
Same Error. 

jared@ubuntu:~/Android/patchrom/epicd710$ make verify
/home/jared/Android/patchrom/build/util.mk:177: **\* multiple target patterns.  Stop.
jared@ubuntu:~/Android/patchrom/epicd710$

**Comment by MasterZen88** [comment]
Well after looking more into util.mk I found a comment talking about local-previous-target-dir. After I added that value to my makefile the error went away.

Does anyone really know what this reference point does: local-previous-target-dir

**Comment by fanoge** [comment]
On 2012年07月28日 00:02, MasterZen88 wrote:

> Well after looking more into util.mk I found a comment talking about local-previous-target-dir. After I added that value to my makefile the error went away.
> 
> Does anyone really know what this reference point does: local-previous-target-dir
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MiCode/patchrom/issues/28#issuecomment-7309105

Used to specify the location to put target zip file for local OTA, it 
should be okay not to set it and leave it as empty.
