### ISSUE TITLE
zhongxing u970 Compile Problems

### ISSUE THREAD

**Issue by xunxun6688** [MiCode/patchrom#33]
/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/u970/out/target_files
zip -q -r -y /media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/u970/out/target_files.zip *
/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/u970
Sign target files
    signing: GameCenter.apk                 (/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/build/security/platform)
Traceback (most recent call last):
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/sign_target_files_apks", line 354, in <module>
    main(sys.argv[1:])
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/sign_target_files_apks", line 341, in main
    SignApks(input_zip, output_zip, apk_key_map, key_passwords)
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/sign_target_files_apks", line 153, in SignApks
    signed_data = SignApk(data, key, key_passwords[key])
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/sign_target_files_apks", line 131, in SignApk
    common.SignFile(unsigned.name, signed.name, keyname, pw, align=4)
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/common.py", line 374, in SignFile
    p = Run(["zipalign", "-f", str(align), sign_name, output_name])
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/common.py", line 62, in Run
    return subprocess.Popen(args, *_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
Build full ota package: /media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/u970/out/fullota.zip
unzipping target target-files...
Traceback (most recent call last):
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/ota_from_target_files", line 876, in <module>
    main(sys.argv[1:])
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/ota_from_target_files", line 828, in main
    OPTIONS.info_dict = common.LoadInfoDict(input_zip)
  File "/media/1275edb8-8d81-4596-9873-b9c3b2012d84/miui/tools/releasetools/common.py", line 111, in LoadInfoDict
    raise ValueError("can't find recovery API version in input target-files")
ValueError: can't find recovery API version in input target-files
make: *_\* [fullota] 错误 1

This is wrong, please help solve it, thank you！！！

**Comment by yu88my** [comment]
No such error when compiling local. It's seem your environment problem.

**Comment by xunxun6688** [comment]
Thank you, really is a problem with my environment, or a year ago, my android sdk version updated yesterday sdk problem solving
