### ISSUE TITLE
make: *** [out/MiuiHome.apk] Error 1

### ISSUE THREAD

**Issue by singhdd93** [MiCode/patchrom#39]
I am trying to build the ROM for lt18i
It has the official support. I downloaded the sources and when I run make fullota it always gives me the same error. I have not modified anything 
Here is the full output of error which i get

> > > build out/MediaProvider.apk...
> > > /home/dds/miui/tools/apktool --quiet b  out/MediaProvider out/MediaProvider.apk
> > > <<< build out/MediaProvider.apk completed!
> > > /home/dds/miui/tools/apktool --quiet d -f /home/dds/miui/miui/system/app/MiuiHome.apk out/MiuiHome
> > > /home/dds/miui/tools/patch_miui_app.sh >/dev/null MiuiHome out/MiuiHome
> > > build out/MiuiHome.apk...
> > > /home/dds/miui/tools/apktool --quiet b  out/MiuiHome out/MiuiHome.apk
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-w320dp-largeui-hdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-w360dp-hugeui-hdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-w360dp-largeui-hdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-w360dp-hugeui-xhdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-largeui-xhdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-hugeui-xhdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/drawable-hugeui-hdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-w360dp-largeui-xhdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-w320dp-hugeui-hdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-largeui-hdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/drawable-largeui-hdpi
> > > invalid resource directory name: /home/dds/miui/lt18i/out/MiuiHome/res/values-hugeui-hdpi
> > > Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL7470284248443911621.tmp, -I, /home/dds/apktool/framework/1.apk, -I, /home/dds/apktool/framework/6.apk, -S, /home/dds/miui/lt18i/out/MiuiHome/res, -M, /home/dds/miui/lt18i/out/MiuiHome/AndroidManifest.xml]
> > >     at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
> > >     at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
> > >     at brut.androlib.Androlib.buildResources(Androlib.java:248)
> > >     at brut.androlib.Androlib.build(Androlib.java:171)
> > >     at brut.androlib.Androlib.build(Androlib.java:154)
> > >     at brut.apktool.Main.cmdBuild(Main.java:182)
> > >     at brut.apktool.Main.main(Main.java:67)
> > > Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL7470284248443911621.tmp, -I, /home/dds/apktool/framework/1.apk, -I, /home/dds/apktool/framework/6.apk, -S, /home/dds/miui/lt18i/out/MiuiHome/res, -M, /home/dds/miui/lt18i/out/MiuiHome/AndroidManifest.xml]
> > >     at brut.util.OS.exec(OS.java:83)
> > >     at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
> > >     ... 6 more
> > > make: **\* [out/MiuiHome.apk] Error 1

Actually I wanted to build for SK17i which has roms similar to LT18i so was trying to build first for this device

**Comment by singhdd93** [comment]
i am using the latest apktool and aapt
apktool 1.5.0
and aapt from http://code.google.com/p/android-apktool/downloads/detail?name=apktool-install-linux-r05-ibot.tar.bz2

**Comment by cmartinbaughman** [comment]
I used to get this error as well on the x515m build. Just run something like this: rm -rf out/MiuiHome/res/_geui_ 
Then if you get this same error in another apk like MiuiSystemUI use rm -rf out/MiuiSystemUI/res/_geui_ . You should be able to see how to match it to fix those errors like this. Note: you shouldn't see ANY ill effect and this should actually go away when they update, as it did for the x515m.

**Comment by yu88my** [comment]
pls use miui's aapt in the tools dir

---

B.R.
余明阳
MIUI系统部
TEL: 18611747740
米聊: 20372646
QQ: 303151288

---

发件人: Damandeep Singh [notifications@github.com]
发送时间: 2012年12月28日 1:39
收件人: MiCode/patchrom
主题: Re: [patchrom] make: **\* [out/MiuiHome.apk] Error 1 (#39)

i am using the latest apktool and aapt
apktool 1.5.0
and aapt from http://code.google.com/p/android-apktool/downloads/detail?name=apktool-install-linux-r05-ibot.tar.bz2

**Comment by singhdd93** [comment]
i didn't change anything in tools dir or any other dir
I have the latest apktool and aapt installed at usr/bin
Should I change that ??

**Comment by yu88my** [comment]
after setting up your build environment,
execute "which aapt" to find out which aapt will be used.
you should replace it with miui's appt.

---

B.R.
余明阳
MIUI系统部
TEL: 18611747740
米聊: 20372646
QQ: 303151288

---

发件人: Damandeep Singh [notifications@github.com]
发送时间: 2012年12月28日 14:02
收件人: MiCode/patchrom
Cc: 余明阳
主题: Re: [patchrom] make: **\* [out/MiuiHome.apk] Error 1 (#39)

i didn't change anything in tools dir or any other dir
I have the latest apktool and aapt installed at usr/bin
Should I change that ??
