### ISSUE TITLE
Service.jar "Bad magic value"

### ISSUE THREAD

**Issue by RomBreaker** [MiCode/patchrom#4]
# /home/insanemod/patchrom/tools/apktool --quiet d -f /home/insanemod/patchrom/miui/system/framework/framework-miui-res.apk out/framework-miui-res
# @ rm -rf out/framework-miui-res/res
# @ cp -r /home/insanemod/patchrom/miui/src/frameworks/miui/core/res/res out/framework-miui-res
# @ for dir in `ls -d overlay/framework-miui-res/res/[^v]*`; do\

```
      #cp -r $dir out/framework-miui-res/res; \
   # done
```
# @echo "  - 2" >> out/framework-miui-res/apktool.yml
# /home/insanemod/patchrom/tools/apktool --quiet b out/framework-miui-res out/framework-miui-res.apk
# @echo "<<< build out/framework-miui-res.apk completed!"

unzip >/dev/null ViciousMIUI-V4-toro-2.3.2-V2-signed.zip -d out/ZIP
/home/insanemod/patchrom/tools/apktool --quiet d -f /home/insanemod/patchrom/miui/system/framework/services.jar out/services_miui
Exception in thread "main" java.lang.RuntimeException: bad magic value: 64 65 78 0a 30 33 35 00
    at org.jf.dexlib.DexFile.<init>(DexFile.java:377)
    at org.jf.dexlib.DexFile.<init>(DexFile.java:274)
    at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:44)
    at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:33)
    at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:68)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:85)
    at brut.apktool.Main.cmdDecode(Main.java:128)
    at brut.apktool.Main.main(Main.java:65)
make: **\* [out/services_miui] Error 1

This is weird.

**Comment by MiuiAnderson** [comment]
This is because you got a ROM which have been done deodex from stock rom. We will release deodex tool this Friday. You can use this tool to deodex a stock ROM which is odexed.

**Comment by RomBreaker** [comment]
I'm have a problem with the "bad magic value"...the Rom I'm using is deodexed..
