### ISSUE TITLE
error during ota_target_from_phone

### ISSUE THREAD

**Issue by jcorrea86** [MiCode/patchrom#41]
I keep getting the below error during a pull from the Razr HD

uid, gid, mode = rows[length-3:] ValueError: need more than 1 value to unpack

Any thoughts why?

**Comment by jcorrea86** [comment]
here is the full error:

using device-specific extensions in .
unable to load device-specific module; assuming none
Traceback (most recent call last):
  File "/home/jr/patchrom/tools/releasetools/ota_from_target_files", line 890, in <module>
    main(sys.argv[1:])
  File "/home/jr/patchrom/tools/releasetools/ota_from_target_files", line 858, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/jr/patchrom/tools/releasetools/ota_from_target_files", line 433, in WriteFullOTAPackage
    Item.GetMetadata(input_zip)
  File "/home/jr/patchrom/tools/releasetools/ota_from_target_files", line 173, in GetMetadata
    uid, gid, mode = rows[length-3:]
ValueError: need more than 1 value to unpack

**Comment by pipi0556** [comment]
I have this problem too, Do you have solve this problem?

**Comment by mohdafix** [comment]
me too
