### ISSUE TITLE
Issue on signing

### ISSUE THREAD

**Issue by sijav** [MiCode/patchrom#45]
> zip -q -r -y /home/sijav/Desktop/patchrom/nypone/out/target_files.zip *
> /home/sijav/Desktop/patchrom/nypone
> Sign target files
> NOT signing: AlipayMsp.apk
>     signing: Userbook.apk                                   (/home/sijav/Desktop/patchrom/build/security/platform)
> Could not create the Java virtual machine.
> 
>   ERROR: signapk.jar failed: return code 1
> 
> Build full ota package: /home/sijav/Desktop/patchrom/nypone/out/fullota.zip
> unzipping target target-files...
> Traceback (most recent call last):
>   File "/home/sijav/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 889, in <module>
>     main(sys.argv[1:])
>   File "/home/sijav/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 841, in main
>     OPTIONS.info_dict = common.LoadInfoDict(input_zip)
>   File "/home/sijav/Desktop/patchrom/tools/releasetools/common.py", line 111, in LoadInfoDict
>     raise ValueError("can't find recovery API version in input target-files")
> ValueError: can't find recovery API version in input target-files
> make: **\* [fullota] Error 1

there is recovery_api_version=3 in first line of META/misc_info.txt
not sure what should I do!
any advise?

**Comment by sijav** [comment]
this was a problem with 32 bit linux system!
it can be solved by run it in a 64bit linux system (better to use ubuntu!)
thnx
