### ISSUE TITLE
Can't build "make fullota"

### ISSUE THREAD

**Issue by fedevd** [MiCode/patchrom#46]
Can't build using "make fullota".. Always have this:

fede@fede-ubuntu:~/patchrom/adv$ make fullota
/home/fede/patchrom/build/util.mk:198: atención: se imponen comandos para el objetivo «stockrom.zip»
/home/fede/patchrom/build/porting.mk:346: atención: se ignoran las instrucciones viejas para el objetivo «stockrom.zip»

> > > build out/framework-res.apk...
> > > add miui overlay resources
> > > WARING[CHECK]: out/framework-res/res/values-largeui-xhdpi : no such directory
> > > WARING[CHECK]: out/framework-res/res/values-mcc460-mnc01 : no such directory
> > > WARING[CHECK]: out/framework-res/res/values-mcc460-mnc01-zh-rCN : no such directory
> > > WARING[CHECK]: out/framework-res/res/values-mcc460-mnc01-zh-rTW : no such directory
> > > WARING[CHECK]: out/framework-res/res/values-mcc460-mnc03 : no such directory
> > > WARING[CHECK]: out/framework-res/res/values-mcc460-mnc03-zh-rCN : no such directory
> > > WARING[CHECK]: out/framework-res/res/values-mcc460-mnc03-zh-rTW : no such directory
> > > /home/fede/patchrom/tools/remove_redef.py >/dev/null out/framework-res
> > > /home/fede/patchrom/tools/apktool --quiet b out/framework-res out/framework-res.apk
> > > /home/fede/patchrom/adv/out/framework-res/res/values/drawables.xml:221: error: Resource entry notification_bg is already defined.
> > > res/drawable/notification_bg.xml:0: Originally defined here.
> > > /home/fede/patchrom/adv/out/framework-res/res/values/drawables.xml:222: error: Resource entry notification_bg_low is already defined.
> > > res/drawable/notification_bg_low.xml:0: Originally defined here.
> > > aapt: warning: string 'app_killed_message' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es hu it ja nl pt ro ru tr
> > > aapt: warning: string 'global_action_choose_profile' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'global_action_reboot' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'global_action_screenshot' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'global_actions_expanded_desktop_mode_off_status' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: da de el es fr hu ja nl pt ro ru
> > > aapt: warning: string 'global_actions_expanded_desktop_mode_on_status' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: da de el es fr hu ja nl pt ro ru
> > > aapt: warning: string 'global_actions_toggle_expanded_desktop_mode' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: da de el es fr hu ja nl pt ro ru
> > > aapt: warning: string 'lockscreen_discharging' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'openurl' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da el es it ja pt tr
> > > aapt: warning: string 'permdesc_preventpower' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da el es hu it ja nl pt tr
> > > aapt: warning: string 'permdesc_sendMockSms' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da el es hu it ja nl pt ru tr
> > > aapt: warning: string 'permlab_preventpower' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da el es hu it ja nl pt tr
> > > aapt: warning: string 'permlab_sendMockSms' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da el es hu it ja nl pt ru tr
> > > aapt: warning: string 'profileGroupCalendar' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'profileGroupEmail' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro tr
> > > aapt: warning: string 'profileGroupGmail' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro tr
> > > aapt: warning: string 'profileGroupPhone' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'profileGroupSMS' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro tr
> > > aapt: warning: string 'profileNameDefault' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'profileNameHome' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'profileNameNight' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'profileNameSilent' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'profileNameWork' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'reboot_bootloader' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt tr
> > > aapt: warning: string 'reboot_bootmenu' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt tr
> > > aapt: warning: string 'reboot_confirm' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'reboot_download' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt tr
> > > aapt: warning: string 'reboot_fastboot' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt tr
> > > aapt: warning: string 'reboot_progress' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'reboot_reboot' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'reboot_recovery' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro tr
> > > aapt: warning: string 'reboot_system' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'storage_sd_dock_card' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da el es hu it ja nl pt tr
> > > aapt: warning: string 'toast_rotation_locked' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da el es it ja nl pt ro tr
> > > aapt: warning: string 'toast_rotation_unlocked' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da el es it ja nl pt ro tr
> > > aapt: warning: string 'weather_0' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_1' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_10' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_11' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_12' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_13' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_14' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_15' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_16' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_17' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_18' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_19' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_2' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_20' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_21' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs dException in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL7964619052125650988.tmp, -x, -S, /home/fede/patchrom/adv/out/framework-res/res, -M, /home/fede/patchrom/adv/out/framework-res/AndroidManifest.xml]
> > >     at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
> > >     at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
> > >     at brut.androlib.Androlib.buildResources(Androlib.java:248)
> > >     at brut.androlib.Androlib.build(Androlib.java:171)
> > >     at brut.androlib.Androlib.build(Androlib.java:154)
> > >     at brut.apktool.Main.cmdBuild(Main.java:182)
> > >     at brut.apktool.Main.main(Main.java:67)
> > > Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL7964619052125650988.tmp, -x, -S, /home/fede/patchrom/adv/out/framework-res/res, -M, /home/fede/patchrom/adv/out/framework-res/AndroidManifest.xml]
> > >     at brut.util.OS.exec(OS.java:83)
> > >     at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
> > >     ... 6 more
> > > a de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_22' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_23' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_24' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_25' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_26' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_27' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_28' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_29' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_3' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_30' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_31' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_32' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_3200' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: de el es hu it ja pt ru tr
> > > aapt: warning: string 'weather_33' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_34' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_35' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_36' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_37' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_38' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_39' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_4' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_40' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_41' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_42' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_43' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_44' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_45' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_46' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_47' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_5' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_6' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_7' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_8' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_9' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_E' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'weather_N' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'weather_NE' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'weather_NW' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'weather_S' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'weather_SE' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'weather_SW' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'weather_W' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > aapt: warning: string 'weather_last_sync_just_now' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_no_data' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_refreshing' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'weather_tap_to_refresh' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ro ru tr
> > > aapt: warning: string 'wildcardProfile' has no default translation in /home/fede/patchrom/adv/out/framework-res/res; found: cs da de el es fr hu it ja nl pt ru tr
> > > make: **\* [out/framework-res.apk] Error 1
> > > fede@fede-ubuntu:~/patchrom/adv$ 

I installed "aapt", "apktool" and "apktool.jar" of MIUI tools and still same error.. What can I do?

**Comment by sijav** [comment]
delete these 2 file!
/home/fede/patchrom/adv/framework-res/res/drawable/notification_bg.xml
/home/fede/patchrom/adv/framework-res/res/drawable/notification_bg_low.xml
and it can get compiled but still you need to fix these translation in your framework-res ...
open /home/fede/patchrom/adv/framework-res/res/values/string.xml
and then open /home/fede/patchrom/adv/framework-res/res/values_es/string.xml
translate all not defined (like wildcardProfile, weather_no_data, etc...) from values_es/string.xml and add them to values/string.xml
you can use Google translator it will make a good translation from Spanish language ;-)
good luck with your patching

**Comment by fedevd** [comment]
Thanks! Worked excellent!! Now I've got this from "android.policy.jar":

/home/fede/patchrom/tools/apktool --quiet d -f /home/fede/patchrom/miui/HDPI/system/framework/android.policy.jar out/android.policy_miui

> > > build out/android.policy.jar...
> > > /home/fede/patchrom/tools/add_miui_smail.sh >/dev/null out/android.policy_miui out/android.policy
> > > /home/fede/patchrom/tools/apktool --quiet b out/android.policy out/android.policy.jar
> > > Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: java.io.FileInputStream@417cff66
> > >     at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
> > >     at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
> > >     at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:64)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:48)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
> > >     at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:222)
> > >     at brut.androlib.Androlib.buildSources(Androlib.java:179)
> > >     at brut.androlib.Androlib.build(Androlib.java:170)
> > >     at brut.androlib.Androlib.build(Androlib.java:154)
> > >     at brut.apktool.Main.cmdBuild(Main.java:182)
> > >     at brut.apktool.Main.main(Main.java:67)
> > > make: **\* [out/android.policy.jar] Error 1

**Comment by sijav** [comment]
do this command=>
smali out/android.policy so we can figure out what is your problem exactly?

**Comment by fedevd** [comment]
fede@fede-ubuntu:~/patchrom/adv$ smali out/android.policy
out/android.policy/smali/com/android/internal/policy/impl/PhoneWindowManager.smali[12245,4] All register args must fit in 4 bits
fede@fede-ubuntu:~/patchrom/adv$

**Comment by sijav** [comment]
go to out/android.policy/smali/com/android/internal/policy/impl and open PhoneWindowsManager.smali and give me from line 12225 to 12265

**Comment by fedevd** [comment]
```
invoke-virtual {v0, v2}, Landroid/os/Message;->setAsynchronous(Z)V

.line 4087
move-object/from16 v0, p0

iget-object v2, v0, Lcom/android/internal/policy/impl/PhoneWindowManager;->mHandler:Landroid/os/Handler;

invoke-static {}, Landroid/view/ViewConfiguration;->getLongPressTimeout()I

move-result v3

int-to-long v3, v3

move-object/from16 v0, v18

invoke-virtual {v2, v0, v3, v4}, Landroid/os/Handler;->sendMessageDelayed(Landroid/os/Message;J)Z

invoke-static {p0}, Lcom/android/internal/policy/impl/PhoneWindowManager$Injector;->sendPowerUpBroadcast(Lcom/android/internal/policy/impl/PhoneWindowManager;)V

goto/16 :goto_3

.line 4082
.end local v8           #newKeyCode:I
.end local v18           #msg:Landroid/os/Message;
:cond_1a
const/16 v8, 0x58

goto :goto_a

.line 4090
:cond_1b
move-object/from16 v0, p0

iget-boolean v2, v0, Lcom/android/internal/policy/impl/PhoneWindowManager;->mVolBtnMusicControls:Z

if-eqz v2, :cond_1c

if-nez v11, :cond_1c

.line 4091
```

**Comment by sijav** [comment]
change p0 to v0 in line 12243 so it will be this =>
invoke-static {p0}, Lcom/android/internal/policy/impl/PhoneWindowManager$Injector;->sendPowerUpBroadcast(Lcom/android/internal/policy/impl/PhoneWindowManager;)V

to this =>
invoke-static {v0}, Lcom/android/internal/policy/impl/PhoneWindowManager$Injector;->sendPowerUpBroadcast(Lcom/android/internal/policy/impl/PhoneWindowManager;)V

**Comment by fedevd** [comment]
Done
Still same error with "smali out/android.policy":

fede@fede-ubuntu:~/patchrom/adv$ smali out/android.policy
out/android.policy/smali/com/android/internal/policy/impl/PhoneWindowManager.smali[12245,4] All register args must fit in 4 bits
fede@fede-ubuntu:~/patchrom/adv$ 

So, still same error when "make fullota" too

**Comment by sijav** [comment]
don't do make fullota it will make the mistake again!
just do it in out folder and save then recompile the android.policy in out directory

**Comment by fedevd** [comment]
Done..

fede@fede-ubuntu:~/patchrom/adv$ cd out
fede@fede-ubuntu:~/patchrom/adv/out$ smali android.policy
fede@fede-ubuntu:~/patchrom/adv/out$ 

Now? What should I have to do?

**Comment by sijav** [comment]
I told you :-D recompile it! It's simple!
/home/fede/patchrom/tools/apktool --quiet b out/android.policy out/android.policy.jar
as simple as it can be :-D
:+1: 
and then continue to make fullota

**Comment by fedevd** [comment]
fede@fede-ubuntu:~/patchrom/adv$ /home/fede/patchrom/tools/apktool --quiet b out/android.policy out/android.policy.jar
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: java.io.FileInputStream@74e8f8c5
    at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
    at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
    at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:64)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:48)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:222)
    at brut.androlib.Androlib.buildSources(Androlib.java:179)
    at brut.androlib.Androlib.build(Androlib.java:170)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
fede@fede-ubuntu:~/patchrom/adv$

**Comment by fedevd** [comment]
That is what I got after run "/home/fede/patchrom/tools/apktool --quiet b out/android.policy out/android.policy.jar"
This and my fever gonna kill me xD

**Comment by sijav** [comment]
again do the smali out/android.policy.jar and if it's the same problem do the same thing on PhoneWindowManager.smali and then type this command ->
/home/fede/patchrom/tools/apktool --quiet b out/android.policy out/android.policy.jar
after that do
make fullota
It's really simple and I have fixed my problem like that!

**Comment by fedevd** [comment]
Done, now framework.jar error :S
It's more harder than it looks this MIUI Patchrom..
This is what I got now afer fix that android.policy and exec "make fullota":

> > > build out/framework.jar...
> > > /home/fede/patchrom/tools/add_miui_smail.sh >/dev/null out/framework_miui out/framework
> > > /home/fede/patchrom/tools/apktool --quiet b out/framework out/framework.jar
> > > Exception in thread "main" org.jf.dexlib.Util.ExceptionWithContext: method index is too large.
> > >     at org.jf.dexlib.Util.ExceptionWithContext.withContext(ExceptionWithContext.java:54)
> > >     at org.jf.dexlib.Item.addExceptionContext(Item.java:176)
> > >     at org.jf.dexlib.Item.writeTo(Item.java:119)
> > >     at org.jf.dexlib.Section.writeTo(Section.java:119)
> > >     at org.jf.dexlib.DexFile.writeTo(DexFile.java:716)
> > >     at brut.androlib.src.DexFileBuilder.getAsByteArray(DexFileBuilder.java:75)
> > >     at brut.androlib.src.DexFileBuilder.writeTo(DexFileBuilder.java:58)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:50)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
> > >     at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:222)
> > >     at brut.androlib.Androlib.buildSources(Androlib.java:179)
> > >     at brut.androlib.Androlib.build(Androlib.java:170)
> > >     at brut.androlib.Androlib.build(Androlib.java:154)
> > >     at brut.apktool.Main.cmdBuild(Main.java:182)
> > >     at brut.apktool.Main.main(Main.java:67)
> > > Caused by: java.lang.RuntimeException: method index is too large.
> > >     at org.jf.dexlib.Code.Format.Instruction35c.writeInstruction(Instruction35c.java:102)
> > >     at org.jf.dexlib.Code.Instruction.write(Instruction.java:57)
> > >     at org.jf.dexlib.CodeItem.writeItem(CodeItem.java:258)
> > >     at org.jf.dexlib.Item.writeTo(Item.java:116)
> > >     ... 12 more
> > > code_item @0x1a9098 (Lcom/google/android/gles_jni/EGLImpl;->eglCreateWindowSurface(Ljavax/microedition/khronos/egl/EGLDisplay;Ljavax/microedition/khronos/egl/EGLConfig;Ljava/lang/Object;[I)Ljavax/microedition/khronos/egl/EGLSurface;)

make: **\* [out/framework.jar] Error 1
fede@fede-ubuntu:~/patchrom/adv$

**Comment by fedevd** [comment]
It's related to this?
https://github.com/MiCode/legacy-patchrom/issues/9

**Comment by sijav** [comment]
Yup it's completly related to this!

**Comment by fedevd** [comment]
2."make .build/framework.jar ",and ignore the error.

Can't do that, no such file or directory...

**Comment by fedevd** [comment]
In XDA, user Gerret told me to split framework.jar in framework.jar and framework2.jar.. Now my doubt is if I take some files of framework.jar and move to a new folder called framework2.jar and start compilation again, will patchrom script recognize that new folder?

**Comment by fedevd** [comment]
Allright, now I passed all that errors.. Now I have this when I exec "make fullota":

#cp other/AxT9IME.apk out/ZIP/system/app
cp stockrom/system/app/FFFFFFFF000000000000000000000001.drbin out/ZIP/system/app
cp: no se puede efectuar `stat' sobre «stockrom/system/app/FFFFFFFF000000000000000000000001.drbin»: No existe el archivo o el directorio
make: **\* [local-pre-zip-misc] Error 1
fede@fede-ubuntu:~/patchrom/adv2$ 

And in the "makefile" I see this in it:

```
#cp other/AxT9IME.apk $(ZIP_DIR)/system/app
cp stockrom/system/app/FFFFFFFF000000000000000000000001.drbin $(ZIP_DIR)/system/app
cp -r stockrom/system/app/mcRegistry $(ZIP_DIR)/system/app
rm -rf $(ZIP_DIR)/system/csc
```

How can I fix that? Or I have to remove that part of code in "makefile"?

**Comment by sijav** [comment]
How did you fix the framework.jar?
By the way what is that in your makefile??
did you made it by yourself?
if you copy that from i9100 I think you should make another one simple and clean!
look at this one => https://github.com/munjeni/miui_sony_xperia/blob/master/stock_lotus/makefile
and also ignore this => local-miui-modified-apps:

**Comment by fedevd** [comment]
Removing those 2 "notif" xml files, thats all..
I used the i9100 makefile, the i9300 makefile..
I have a Samsung Advance, nearly close to S2 and still being impossible to build, even if I replace the base files on i9100 folder with mines..

**Comment by fedevd** [comment]
Don't you wanna add me on Google Hangouts? Maybe it's better to talk over there.. Anyway I ported from S2 MIUI v4and works fine but I have a bug that I can't solve it, even if I patch smalis, can't fix it. Plus that i want to make a thread in XDA with most common errors faced with Patchrom and possible fixes.

**Comment by sijav** [comment]
I don't have a google hangout
anyway I mean framework.jar not frameowrk-res.apk
care to give your logcat to see what is your problem in?

**Comment by fedevd** [comment]
Get into i9300 repo and download the framework script at the end of the list, don't remember the name

Sina notifications@github.com wrote:

I don't have a google hangout
anyway I mean framework.jar not frameowrk-res.apk
care to give your logcat to see what is your problem in?

---
