### ISSUE TITLE
build failure - error OverflowError: size does not fit in an int

### ISSUE THREAD

**Issue by rickysarraf** [MiCode/patchrom#51]
This looks like a python error but I thought of checking here first.

There's one more exception in the logs:
Traceback (most recent call last):
  File "/media/DATA/Android/patchrom/tools/releasetools/ota_from_target_files", line 889, in <module>

I'm not sure what this is about.
# Full Log

Run getfilesysteminfo and recoverylink.py to recover symlink
Recovery link files success
Build apkcerts.txt
remote object '/data/system/packages.xml' does not exist
Error: /media/DATA/Android/patchrom/gn878/out/target_files/packages.xml doesn't exist or isn't a vaild xml file
rm: cannot remove ‘/media/DATA/Android/patchrom/gn878/out/target_files/packages.xml’: No such file or directory
Generate metadata used to build target files...
Compress the target_files dir into zip file
/media/DATA/Android/patchrom/gn878
Build full ota package: /media/DATA/Android/patchrom/gn878/stockrom.zip
Traceback (most recent call last):
  File "/media/DATA/Android/patchrom/tools/releasetools/ota_from_target_files", line 889, in <module>
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
using prebuilt boot.img...
    main(sys.argv[1:])
  File "/media/DATA/Android/patchrom/tools/releasetools/ota_from_target_files", line 857, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/media/DATA/Android/patchrom/tools/releasetools/ota_from_target_files", line 440, in WriteFullOTAPackage
    common.ZipWriteStr(output_zip, "boot.img", boot_img.data)
  File "/media/DATA/Android/patchrom/tools/releasetools/common.py", line 618, in ZipWriteStr
    zip.writestr(zinfo, data)
  File "/usr/lib/python2.7/zipfile.py", line 1218, in writestr
    self._writecheck(zinfo)
  File "/usr/lib/python2.7/zipfile.py", line 1102, in _writecheck
    raise LargeZipFile("Filesize would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions

**Comment by rickysarraf** [comment]
And here's the explanation from the python docs:

compression is the ZIP compression method to use when writing the archive, and should be ZIP_STORED or ZIP_DEFLATED; unrecognized values will cause RuntimeError to be raised. If ZIP_DEFLATED is specified but the zlib module is not available, RuntimeError is also raised. The default is ZIP_STORED. If allowZip64 is True zipfile will create ZIP files that use the ZIP64 extensions when the zipfile is larger than 2 GB. If it is false (the default) zipfile will raise an exception when the ZIP file would require ZIP64 extensions. ZIP64 extensions are disabled by default because the default zip and unzip commands on Unix (the InfoZIP utilities) don’t support these extensions.

So, the file we are creating, i.e. stockrom.zip is larger than 2 GiB. Is this expected?

**Comment by rickysarraf** [comment]
So the following change fixes the reported bug (sorry, I didn't provide the diff. I just quickly want you guys to know)

The changed line is: compression=zipfile.ZIP_DEFLATED,allowZip64=True)

  temp_zip_file = tempfile.NamedTemporaryFile()
  output_zip = zipfile.ZipFile(temp_zip_file, "w",
                               compression=zipfile.ZIP_DEFLATED,allowZip64=True)

  if OPTIONS.incremental_source is None:
    WriteFullOTAPackage(input_zip, output_zip)
    if OPTIONS.package_key is None:
      OPTIONS.package_key = OPTIONS.info_dict.get(
          "default_system_dev_certificate",
          "build/target/product/security/testkey")
  else:
    print "unzipping source target-files..."
    OPTIONS.source_tmp, source_zip = common.UnzipTemp(OPTIONS.incremental_source)
    OPTIONS.target_info_dict = OPTIONS.info_dict
    OPTIONS.source_info_dict = common.LoadInfoDict(source_zip)
    if OPTIONS.package_key is None:
"releasetools/ota_from_target_files" 894L, 32074C written                                                            853,50        96%

**Comment by rickysarraf** [comment]
But this further leads to another exception:

Build full ota package: /media/DATA/Android/patchrom/gn878/stockrom.zip
Traceback (most recent call last):
  File "/media/DATA/Android/patchrom/tools/releasetools/ota_from_target_files", line 889, in <module>
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
using prebuilt boot.img...
    main(sys.argv[1:])
  File "/media/DATA/Android/patchrom/tools/releasetools/ota_from_target_files", line 857, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/media/DATA/Android/patchrom/tools/releasetools/ota_from_target_files", line 440, in WriteFullOTAPackage
    common.ZipWriteStr(output_zip, "boot.img", boot_img.data)
  File "/media/DATA/Android/patchrom/tools/releasetools/common.py", line 618, in ZipWriteStr
    zip.writestr(zinfo, data)
  File "/usr/lib/python2.7/zipfile.py", line 1220, in writestr
    zinfo.CRC = crc32(bytes) & 0xffffffff       # CRC-32 checksum
OverflowError: size does not fit in an int

Which I understand given that the size is way too big. I am wondering how I should work around it.

**Comment by rickysarraf** [comment]
Are there good reasons why zip.writestr() has been used?
What I've hit is this: http://bugs.python.org/issue1060

**Comment by rickysarraf** [comment]
THe root of the bloody problem lies elsewhere. Look at this:

rrs@zan:/media/DATA/Android/patchrom/gn878/out/target_files$ ls -lh BOOTABLE_IMAGES/
total 2.7G
-rw-r--r-- 1 rrs rrs 2.7G Jun 27 23:26 boot.img
-rw-r--r-- 1 rrs rrs 2.6M Jun 27 23:20 recovery.img

2.7 GiB and counting for boot.img. Sigh!!!!

So this is the snippet to get boot.img:

```
else
    local info=`adb shell cat /etc/recovery.fstab | grep boot | sed -e "s/\s\+/:/g"`
    local fstype=`echo $info | cut -d":" -f2`

    if [ "$fstype" == "mtd" ]; then
        mtdn=`adb shell cat /proc/mtd | grep boot | cut -f1 -d":"`
        device=/dev/$fstype/$mtdn
    else
        device=`echo $info | cut -d":" -f3`
    fi
    adb pull $device $TARGET_FILES_DIR/BOOTABLE_IMAGES/boot.img
fi
```

And the culprit here:

rrs@zan:~/devel/jpmc (master)$ adb shell cat /etc/recovery.fstab | grep boot | sed -e "s/\s+/:/g"
/boot:emmc:/dev/bootimg:

**Comment by rickysarraf** [comment]
Okay!! I guess I've root caused it. The tools/releasetools/ota_target_from_phone tool currently does not support MTK boot image format.

**Comment by rickysarraf** [comment]
Yup!! I was right. Finally got my stockrom.zip to proceed further. Closing this bug report.
