### ISSUE TITLE
cant' build framework.jar

### ISSUE THREAD

**Issue by rickysarraf** [MiCode/patchrom#52]
rrs@zan:/media/DATA/Android/patchrom/gn878$ make fullota

> > > build out/framework.jar...
> > > /media/DATA/Android/patchrom/tools/add_miui_smail.sh >/dev/null out/framework_miui out/framework
> > > /media/DATA/Android/patchrom/tools/apktool --quiet b out/framework out/framework.jar
> > > Exception in thread "main" org.jf.dexlib.Util.ExceptionWithContext: method index is too large.
> > >         at org.jf.dexlib.Util.ExceptionWithContext.withContext(ExceptionWithContext.java:54)
> > >         at org.jf.dexlib.Item.addExceptionContext(Item.java:176)
> > >         at org.jf.dexlib.Item.writeTo(Item.java:119)
> > >         at org.jf.dexlib.Section.writeTo(Section.java:119)
> > >         at org.jf.dexlib.DexFile.writeTo(DexFile.java:716)
> > >         at brut.androlib.src.DexFileBuilder.getAsByteArray(DexFileBuilder.java:75)
> > >         at brut.androlib.src.DexFileBuilder.writeTo(DexFileBuilder.java:58)
> > >         at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:50)
> > >         at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
> > >         at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:222)
> > >         at brut.androlib.Androlib.buildSources(Androlib.java:179)
> > >         at brut.androlib.Androlib.build(Androlib.java:170)
> > >         at brut.androlib.Androlib.build(Androlib.java:154)
> > >         at brut.apktool.Main.cmdBuild(Main.java:182)
> > >         at brut.apktool.Main.main(Main.java:67)
> > > Caused by: java.lang.RuntimeException: method index is too large.
> > >         at org.jf.dexlib.Code.Format.Instruction35c.writeInstruction(Instruction35c.java:102)
> > >         at org.jf.dexlib.Code.Instruction.write(Instruction.java:57)
> > >         at org.jf.dexlib.CodeItem.writeItem(CodeItem.java:258)
> > >         at org.jf.dexlib.Item.writeTo(Item.java:116)
> > >         ... 12 more
> > > code_item @0x1d78b4 (Ljavax/microedition/khronos/egl/EGLContext;-><clinit>()V)

make: **\* [out/framework.jar] Error 1

I am stuck at this step and am not sure how to proceed further.. :-(
Any help is appreciated

**Comment by dhruvbatra205** [comment]
https://github.com/MiCode/patchrom/issues/46
