### ISSUE TITLE
Error when zipping

### ISSUE THREAD

**Issue by programmerlapar** [MiCode/patchrom#58]
Recovery link files success
Compress the target_files dir into zip file
/home/pirmansaah/patchrom/huashan/out/target_files
zip -q -r -y /home/pirmansaah/patchrom/huashan/out/target_files.zip *

zip error: Zip file structure invalid (/home/pirmansaah/patchrom/huashan/out/target_files.zip)
/home/pirmansaah/patchrom/huashan
Sign target files
Traceback (most recent call last):
  File "/home/pirmansaah/patchrom/tools/releasetools/sign_target_files_apks", li

ne 354, in <module>
    main(sys.argv[1:])
  File "/home/pirmansaah/patchrom/tools/releasetools/sign_target_files_apks", line 330, in main
    input_zip = zipfile.ZipFile(args[0], "r")
  File "/usr/lib/python2.7/zipfile.py", line 714, in **init**
    self._GetContents()
  File "/usr/lib/python2.7/zipfile.py", line 748, in _GetContents
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 763, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
mv: cannot stat `temp.zip': No such file or directory
Build full ota package: /home/pirmansaah/patchrom/huashan/out/fullota.zip
unzipping target target-files...
[/home/pirmansaah/patchrom/huashan/out/target_files.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/pirmansaah/patchrom/huashan/out/target_files.zip or
        /home/pirmansaah/patchrom/huashan/out/target_files.zip.zip, and cannot find /home/pirmansaah/patchrom/huashan/out/target_files.zip.ZIP, period.

   ERROR: failed to unzip input target-files "/home/pirmansaah/patchrom/huashan/out/target_files.zip"

make: **\* [fullota] Error 1

**Comment by programmerlapar** [comment]
anyone?

**Comment by programmerlapar** [comment]
I solved this problem.
please closed this one :)

**Comment by viasyllable** [comment]
how to solve this problem ?
