### ISSUE TITLE
Error on boot (DHD)

### ISSUE THREAD

**Issue by iBotPeaches** [MiCode/patchrom#6]
I've re-done the smali edits 4 times now. I've actually re-done the entire process 4 times because I thought I was making a mistake.

```
I/SystemServer( 1420): Alarm Manager
E/PhonePolicy( 1420): Could not preload class for phone policy: com.android.internal.policy.impl.PhoneWindow$ContextMenuCallback
I/SystemServer( 1420): Init Watchdog
I/SystemServer( 1420): Window Manager
W/dalvikvm( 1420): VFY: register1 v0 type 0, wanted 17
W/dalvikvm( 1420): VFY:  rejecting opcode 0xd5 at 0x002f
W/dalvikvm( 1420): VFY:  rejected Lcom/android/internal/policy/impl/PhoneWindowManager;.interceptKeyBeforeQueueing (Landroid/view/KeyEvent;IZ)I
W/dalvikvm( 1420): Verifier rejected class Lcom/android/internal/policy/impl/PhoneWindowManager;
W/dalvikvm( 1420): threadid=23: thread exiting with uncaught exception (group=0x409e81f8)
I/Process ( 1420): Sending signal. PID: 1420 SIG: 9
E/AndroidRuntime( 1420): *** FATAL EXCEPTION IN SYSTEM PROCESS: WindowManager
E/AndroidRuntime( 1420): java.lang.VerifyError: com/android/internal/policy/impl/PhoneWindowManager
E/AndroidRuntime( 1420):    at com.android.internal.policy.impl.MiuiClassFactory.createPhoneWindowManager(MiuiClassFactory.java:32)
E/AndroidRuntime( 1420):    at com.android.internal.policy.impl.Policy.makeNewWindowManager(Policy.java)
E/AndroidRuntime( 1420):    at com.android.internal.policy.PolicyManager.makeNewWindowManager(PolicyManager.java:67)
E/AndroidRuntime( 1420):    at com.android.server.wm.WindowManagerService.<init>(WindowManagerService.java:306)
E/AndroidRuntime( 1420):    at com.android.server.wm.WindowManagerService.<init>(WindowManagerService.java:145)
E/AndroidRuntime( 1420):    at com.android.server.wm.WindowManagerService$WMThread.run(WindowManagerService.java:689)
I/ServiceManager( 1303): service 'sensorservice' died
I/ServiceManager( 1303): service 'meminfo' died
I/ServiceManager( 1303): service 'activity' died
I/ServiceManager( 1303): service 'entropy' died
I/ServiceManager( 1303): service 'power' died
I/ServiceManager( 1303): service 'batteryinfo' died
I/ServiceManager( 1303): service 'usagestats' died
I/ServiceManager( 1303): service 'telephony.registry' died
I/ServiceManager( 1303): service 'package' died
```

Can not fix that. One of my smali edits told me to edit PhoneManager$18$1, but I only had PhoneManager$18. Could that be the problem? How do I do that smali edit, if I don't have that file?

**Comment by MiuiAnderson** [comment]
You can check if PhoneWindowManager$18 in your device matches PhoneWindowManager$18 on android directory.  The internal class naming will vary according to device. You can refer to HTC sensation. And, seems that DHD has no stock 4.0 rom. The patchrom ics branch requires 4.0 rom.

**Comment by iBotPeaches** [comment]
Well, I've been using this as a base http://forum.xda-developers.com/showthread.php?t=1450962

Its Ice Cold Sandwich ICS 4.0 by LorD ClockaN. 

The PhoneWindowManager between my DHD and the /android folder and /sensation folder are massively different. I guess I'll just replace em and see if I can get a boot without this java.lang.VerifyError

Thanks for the help.
