### ISSUE TITLE
Porting new device

### ISSUE THREAD

**Issue by djsuca** [MiCode/patchrom#62]
hi there, 

tnks for the great work...

i've a alcatem OT6030X that is running Lewa rom fine, but i would like to port a MIUI for it, and followind you tutorial:

1) connect your device to PC, ensure adb works - Done

(2) run the following commands - Done

```
 . build/envsetup.sh - Done

 mkdir xblade - Done in My case i've created ot6030x

 cd xblade  - Done ot6030x

 adb reboot recovery - Done

 ../tools/releasetools/ota_target_from_phone -r (this will generate a stockrom.zip, flash this zip in recovery mode to ensure it works) - On this step gives me this error:
```
#2

/home/dj_suca/patchrom/ot6030x
Build full ota package: /home/dj_suca/patchrom/ot6030x/stockrom.zip
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
using prebuilt boot.img...
Traceback (most recent call last):
  File "/home/dj_suca/patchrom/tools/releasetools/ota_from_target_files", line 889, in <module>
    main(sys.argv[1:])
  File "/home/dj_suca/patchrom/tools/releasetools/ota_from_target_files", line 857, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/dj_suca/patchrom/tools/releasetools/ota_from_target_files", line 428, in WriteFullOTAPackage
    OPTIONS.input_tmp, "BOOT")
  File "/home/dj_suca/patchrom/tools/releasetools/common.py", line 264, in GetBootableImage
    return File.FromLocalFile(name, prebuilt_path)
  File "/home/dj_suca/patchrom/tools/releasetools/common.py", line 699, in FromLocalFile
    data = f.read()
OverflowError: requested number of bytes is more than a Python string can hold
# 

A file is Create on /home/dj_suca/patchrom/ot6030x/out/target_files.zip

but cant be flashed to mobile..

and i dont know if a can continue with the followed steps:

```
 cp ../honor/makefile .(modify the local-zip-file to stockrom.zip, read the comments in makefile)

 make workspace

 make firstpatch (this will add the miui code into framework/android.policy/services.jar, resolve any conflict)

 make fullota
```

Can some one please help me.. i really would like to have miui on this phone

**Comment by Javier-Alonso** [comment]
No, you can't continue. If you're using stock rom, have you deodex it?

**Comment by Javier-Alonso** [comment]
The tager-files.zip is not the extracted files zip. I should be name "stockrom.zip"
