### ISSUE TITLE
Issues when porting

### ISSUE THREAD

**Issue by abielzulio** [MiCode/patchrom#67]
> unzip >/dev/null  "system/framework/_.apk" -d out
> unzip:  cannot find or open system/framework/_.apk, system/framework/_.apk.zip or
> system/framework/_.apk.ZIP.
> 
> No zipfiles found.
> make: **\* [out/apktool-if] Error 9

What should i do?

**Comment by cmbaughman** [comment]
I just looked closer at your error and it looks like the build process can't find your stockroom.zip? Did you follow the other steps? Boot into recovery and do:

```
source build/envsetup.sh
mkdir YOURDEVICE
cd YOURDEVICE
../tools/releasetools/ota_target_from_phone -r
cp ../YOURDEVICE/makefile .
make workspace
make firstpatch
```

Following those steps will get you started for MIUI development. It will create the difference files that you simply use to patch and port your device. 

Please let us know which device you are trying to build or port, and which branch you are attempting (also which OS you are running this from) and we can help you solve the issue. It's much easier if you are on Linux or Mac.

**Comment by abielzulio** [comment]
Okay, my first issues has been fixed by edit my device makefile.

Now i got this error 

> unzip >/dev/null /home/fantastical/workspace/android/patchrom/taoshan/out/target_files.zip 
> "system/framework/_.apk" -d out
> caution: filename not matched:  system/framework/_.apk
> make: **\* [out/apktool-if] Error 11

I am trying to build for taoshan (Sony Xperia L) with kitkat branch. I am used CM/FXP (4.4.4) as base. I am on Ubuntu 14.10.

BTW seems it generated target_files.zip, not stockrom.zip.

**Comment by abielzulio** [comment]
Can you help me to set up my device makefile? @cmbaughman

**Comment by ghost** [comment]
To fix just rename target_files.zip to stockrom.zip like it says on the makefile and drag the .zip out of the "out" folder but keep it in the xblade(or whatever you named it) folder.

Then type the "make workspace"

**Comment by abielzulio** [comment]
Error still same

Would you like to check taoshan makefile here https://github.com/abielzuliom/taoshan-patchrom/blob/master/Makefile ? 

It seems messed out @RealiableCandy4

**Comment by ghost** [comment]
Try downloading cyanogenmod ROM and renaming the .zip to stockrom.zip then replacing it with the one in xblade folder and see what happens when you "make workspace"

**Comment by abielzulio** [comment]
I used FreeXperia Project (CM for Xperia) at this moment

EDIT: Now is working! Thanks for the tip!

BTW how to do clean workspace in case i want to start "make workspace" again from zero? @RealiableCandy4

**Comment by abielzulio** [comment]
Now i have a new problem again when do "make fullota"

build out/services.jar...
#@ rm -rf out/services.jar.out
/home/fantastical/patchrom/tools/apktool --quiet b out/services.jar.out out/services.jar
[738,10] Label "goto_miui" is not defined.
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: /home/fantastical/patchrom/taoshan/out/services.jar.out/smali/com/android/server/NetworkManagementService.smali
        at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
        at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
        at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:66)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:50)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:257)
        at brut.androlib.Androlib.buildSources(Androlib.java:214)
        at brut.androlib.Androlib.build(Androlib.java:205)
        at brut.androlib.Androlib.build(Androlib.java:176)
        at brut.apktool.Main.cmdBuild(Main.java:228)
        at brut.apktool.Main.main(Main.java:79)
make: **\* [out/services.jar] Error 1

> http://pastebin.com/C1yLZGur

What to do now? I give up at smali '_'

**Comment by minhdangoz** [comment]
Make a png image with name is ic_lockscreen_ime.png then put it to
res/drawable-hdpi
Vào 21-07-2014 18:43, "Abiel Zulio M" notifications@github.com đã viết:

**Comment by abielzulio** [comment]
Already fixed that by take ic_lockscreen_ime.png from my Android SDK (xxhdpi) and then put it to my framework-res/res/drawable-xxhdpi

But my phone is HDPI, it is okay? I don't know how to resize it even make a new one as you talked about.

xxhdpi : 90x90
hdpi : 36x36 (i guess)

**Comment by minhdangoz** [comment]
48x48

**Comment by abielzulio** [comment]
How about this issue? Trying to make fullota but i faced this. Can someone help me at smali? :|

http://pastebin.com/C1yLZGur

**Comment by minhdangoz** [comment]
Did you resolve all the conflicts in temp/reject?

**Comment by abielzulio** [comment]
What should i do with this smali? http://pastebin.com/GgeQMG73

In my errors said 

> [738,10] Label "goto_miui" is not defined.

How to define that?

**Comment by minhdangoz** [comment]
Haha, I have no idea !

**Comment by abielzulio** [comment]
Lol, thought you were master at this.

New error again :|

build out/services.jar...
#@ rm -rf out/services.jar.out
/home/fantastical/patchrom/tools/apktool --quiet b out/services.jar.out out/services.jar
Ignoring duplicate virtual method definition: Lcom/android/server/StatusBarManagerService;->setStatus(ILandroid/os/IBinder;Ljava/lang/String;Landroid/os/Bundle;)V
Ignoring duplicate virtual method definition: Lcom/android/server/LockSettingsService;->setRawLockPassword([BI)V
[738,10] Label "goto_miui" is not defined.
[1004,10] Label "goto_miui" is not defined.
[1008,25] mismatched tree node: Landroid/net/RouteInfo; expecting I_CATCHES
[1012,4] mismatched tree node: I_STATEMENT_FORMAT35c_METHOD expecting <UP>
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: /home/fantastical/patchrom/taoshan/out/services.jar.out/smali/com/android/server/NetworkManagementService.smali
    at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
    at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
    at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:66)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:50)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:257)
    at brut.androlib.Androlib.buildSources(Androlib.java:214)
    at brut.androlib.Androlib.build(Androlib.java:205)
    at brut.androlib.Androlib.build(Androlib.java:176)
    at brut.apktool.Main.cmdBuild(Main.java:228)
    at brut.apktool.Main.main(Main.java:79)
make: **\* [out/services.jar] Error 1

**Comment by abielzulio** [comment]
No help? :(

**Comment by minhdangoz** [comment]
You must resolve the conflicts
Have you ever patch file?
for example
patch -p1 < filename.diff

And you get the same issue like the first time I have patched MIUI.
Go to out/temp/reject
open the *.rej files.
focus to "!", "-" and "+"
! means you need to edit, replace...
- remove
- add, append...
  Compare android_smali vs miui_smali
  you you will the changes betwwen android_smali (AOSP) vs miui_smali
  Compare $device_dir/smali vs android_smali
  ....
  very hard !
  you should better give up !

**Comment by abielzulio** [comment]
@minhdangoz How about you? Did you gave up too?

**Comment by minhdangoz** [comment]
No. I have done
Vào 31-07-2014 13:26, "Abiel Zulio M" notifications@github.com đã viết:

**Comment by abielzulio** [comment]
Then how did you fixed that?

**Comment by minhdangoz** [comment]
I said that you must resolve the conflicts !

2014-07-31 15:49 GMT+07:00 Abiel Zulio M notifications@github.com:

> Then how did you fixed that?
> On Jul 31, 2014 1:37 PM, "minhdangoz" notifications@github.com wrote:
> 
> > No. I have done
> > Vào 31-07-2014 13:26, "Abiel Zulio M" notifications@github.com đã
> > viết:
> > 
> > > @minhdangoz https://github.com/minhdangoz How about you? Did you
> > > gave
> > > up too?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/MiCode/patchrom/issues/67#issuecomment-50717838.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MiCode/patchrom/issues/67#issuecomment-50719246.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MiCode/patchrom/issues/67#issuecomment-50733400.

## 

Thanks and Best regards,

Jimmy Lâm
