### ISSUE TITLE
Last step Prob 

### ISSUE THREAD

**Issue by Zoldyck07** [MiCode/patchrom#72]
Compress the target_files dir into zip file
/home/zoldyck/patchrom/nicki/out/target_files
zip -q -r -y /home/zoldyck/patchrom/nicki/out/target_files.zip *

zip error: Zip file structure invalid (/home/zoldyck/patchrom/nicki/out/target_files.zip)
/home/zoldyck/patchrom/nicki
Sign target files
Traceback (most recent call last):
  File "/home/zoldyck/patchrom/tools/releasetools/sign_target_files_apks", line 354, in <module>
    main(sys.argv[1:])
  File "/home/zoldyck/patchrom/tools/releasetools/sign_target_files_apks", line 330, in main
    input_zip = zipfile.ZipFile(args[0], "r")
  File "/usr/lib/python2.7/zipfile.py", line 770, in **init**
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
mv: cannot stat ‘temp.zip’: No such file or directory
Build full ota package: /home/zoldyck/patchrom/nicki/out/fullota.zip
unzipping target target-files...
[/home/zoldyck/patchrom/nicki/out/target_files.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/zoldyck/patchrom/nicki/out/target_files.zip or
        /home/zoldyck/patchrom/nicki/out/target_files.zip.zip, and cannot find /home/zoldyck/patchrom/nicki/out/target_files.zip.ZIP, period.

   ERROR: failed to unzip input target-files "/home/zoldyck/patchrom/nicki/out/target_files.zip"

make: **\* [fullota] Error 1

Anyone know how to fix that?

**Comment by kat0072** [comment]
To fix this delete the existing Target_Files.zip from your OUT folder and run the same command again.
You can find that zip at this location: /home/zoldyck/patchrom/nicki/out/
