### ISSUE TITLE
Issues with 'ota_target_from_phone'

### ISSUE THREAD

**Issue by fedevd** [MiCode/patchrom#73]
How can I fix this? I am trying to build it for Nexus 4. Flashed stock 4.4.4. Worked before but now that I had to sync the source again is not working. It can't create stockrom.zip

$. build/envsetup.sh

federico@Aspire-Z3761:~/patchrom$ . build/envsetup.sh
PATCHROM_BRANCH  = kitkat
ANDROID_PLATFORM = v19
PORT_ROOT        = /home/federico/patchrom
ANDROID_TOP      = 
ANDROID_OUT      = 
PORT_PRODUCT     = Unknown
USE_ANDROID_OUT  = 
ANDROID_BRANCH   = 

$ mkdir mako
$ cd mako
$ ../tools/releasetools/ota_target_from_phone -r

1408 files pulled. 0 files skipped.
3539 KB/s (739489399 bytes in 204.005s)
Remount /system to be writable
remount succeeded
Run getfilesysteminfo to build filesystem_config.txt
113 KB/s (5572 bytes in 0.048s)
Run getfilesysteminfo and recoverylink.py to recover symlink
Recovery link files success
Build apkcerts.txt
2264 KB/s (139142 bytes in 0.059s)
Generate metadata used to build target files...
Compress the target_files dir into zip file
/home/federico/patchrom/mako
Build full ota package: /home/federico/patchrom/mako/stockrom.zip
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
Traceback (most recent call last):
  File "/home/federico/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/federico/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/federico/patchrom/tools/releasetools/ota_from_target_files", line 401, in WriteFullOTAPackage
    device_specific.FullOTA_Assertions()
  File "/home/federico/patchrom/tools/releasetools/common.py", line 690, in FullOTA_Assertions
    return self._DoCall("FullOTA_Assertions")
  File "/home/federico/patchrom/tools/releasetools/common.py", line 679, in _DoCall
    getattr(self.miui_module, function_name)(_((self,) + args), *_kwargs)
  File "/home/federico/patchrom/tools/releasetools/miui_releasetools.py", line 6, in FullOTA_Assertions
    info.script.Mount("/data")
  File "/home/federico/patchrom/tools/releasetools/edify_generator.py", line 140, in Mount
    p = fstab[mount_point]
KeyError: '/data'

**Comment by 0x1001u** [comment]
I got the same problem! :-(

**Comment by fedevd** [comment]
Hmmm, you gotta revert 2 commits.. Send me a message on Hangouts, my mail is dfmelano@gmail.com, I am to drunk to answer you rite now but I will help you over Hangouts tomorrow LOL.. Send me a message and I will tell you how to solve that issue =P

**Comment by 0x1001u** [comment]
Hi fedevd.I am delighted to receive your message. I had the same issues when I run "ota_target_from_phone -r".my phone is samsung note3 n900p. PhilZ touch 6 recovery.This problem has troubled me for a long time!Eager for your help！Thanks a lot！

**Comment by huiyiqun** [comment]
Obviously, there is not mount point named 'data'.
