### ISSUE TITLE
Build full ota package

### ISSUE THREAD

**Issue by mohdafix** [MiCode/patchrom#76]
Please help me with this issue.

Build full ota package: /home/afix/patchrom/alpha/stockrom.zip
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
using prebuilt boot.img...
Traceback (most recent call last):
  File "/home/afix/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/afix/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/afix/patchrom/tools/releasetools/ota_from_target_files", line 432, in WriteFullOTAPackage
    Item.GetMetadata(input_zip)
  File "/home/afix/patchrom/tools/releasetools/ota_from_target_files", line 163, in GetMetadata
    name, uid, gid, mode = columns[:4]
ValueError: need more than 2 values to unpack
afix@ubuntu:~/patchrom/alpha$

**Comment by zdunex25** [comment]
show your filesystem_config.txt
