### ISSUE TITLE
Error building miui for i9506

### ISSUE THREAD

**Issue by fralaxy** [MiCode/patchrom#77]
Hi. I am trying to build a MIUI v5 for my galaxy s4 lte-a, (sd800, 2gb, adreno 330), based on slimkitkat.

But, always (changing the rom and recovery) (cwm tryed and phiz and twrp too), i get the same error:

Build full ota package: /home/fran/patchrom/ltep/stockrom.zip
unzipping target target-files...
using device-specific extensions in .
using device-specific extensions in .
Traceback (most recent call last):
  File "/home/fran/patchrom/tools/releasetools/ota_from_target_files", line 880, in <module>
    main(sys.argv[1:])
  File "/home/fran/patchrom/tools/releasetools/ota_from_target_files", line 848, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/fran/patchrom/tools/releasetools/ota_from_target_files", line 389, in WriteFullOTAPackage
    metadata=metadata,
NameError: global name 'metadata' is not defined

What's happend?

Please help me! Thanks.

**Comment by fralaxy** [comment]
UPP! HELP ME

**Comment by fralaxy** [comment]
UP!
