### ISSUE TITLE
MIUI6 patchrom 出现 Exception in thread "main" java.lang.IllegalStateException: Cannot get the location of a label that hasn't been placed yet.

### ISSUE THREAD

**Issue by pexcn** [MiCode/patchrom#79]
make fullota 出现如下错误，但是单独用 /home/pexcn/pexcn/Android/source/miui6/tools/apktool b out/services -o out/services.jar 就不会有这个问题，请问如何修复呢？

/home/pexcn/pexcn/Android/source/miui6/tools/overlay_smali.sh >/dev/null out/services /home/pexcn/pexcn/Android/source/miui6/android/overlay
/home/pexcn/pexcn/Android/source/miui6/tools/add_miui_smail.sh >/dev/null out/services_miui out/services
/home/pexcn/pexcn/Android/source/miui6/tools/apktool --quiet b out/services -o out/services.jar
Exception in thread "main" java.lang.IllegalStateException: Cannot get the location of a label that hasn't been placed yet.
    at org.jf.dexlib2.builder.Label.getLocation(Label.java:54)
    at org.jf.dexlib2.builder.Label.getCodeAddress(Label.java:48)
    at org.jf.dexlib2.builder.BuilderOffsetInstruction.internalGetCodeOffset(BuilderOffsetInstruction.java:60)
    at org.jf.dexlib2.builder.BuilderOffsetInstruction.getCodeOffset(BuilderOffsetInstruction.java:50)
    at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:189)
    at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:954)
    at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:769)
    at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:222)
    at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:200)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:57)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:354)
    at brut.androlib.Androlib.buildSources(Androlib.java:294)
    at brut.androlib.Androlib.build(Androlib.java:280)
    at brut.androlib.Androlib.build(Androlib.java:255)
    at brut.apktool.Main.cmdBuild(Main.java:225)
    at brut.apktool.Main.main(Main.java:84)
make: **\* [out/services.jar] 错误 1

**Comment by zdunex25** [comment]
Did you merge rejects to services.jar?

**Comment by pexcn** [comment]
@zdunex25 把 --quiet 的参数去掉也没提示错误在哪行，但是再单独用apktool回编译一遍就可以成功了
