### ISSUE TITLE
ota_target_from_phone error at recoverylink.py and blow

### ISSUE THREAD

**Issue by larnk** [MiCode/patchrom#80]
I have tried running ota_target_from_phone on my htc e8( model: stm8)  and get error like blow:
Remount /system to be writable
remount succeeded
Run getfilesysteminfo to build filesystem_config.txt
103 KB/s (5572 bytes in 0.052s)
Run getfilesysteminfo and recoverylink.py to recover symlink
Traceback (most recent call last):
  File "/home/android/patchrom/tools/releasetools/recoverylink.py", line 16, in <module>
    target = '/' + filepath[1]
IndexError: list index out of range
Build apkcerts.txt
943 KB/s (288166 bytes in 0.298s)
Traceback (most recent call last):
  File "/home/android/patchrom/tools/apkcerts.py", line 65, in <module>
    main()
  File "/home/android/patchrom/tools/apkcerts.py", line 34, in main
    name = getName(pkg.attributes["codePath"].value)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 522, in **getitem**
    return self._attrs[attname_or_tuple]
KeyError: 'codePath'
Generate metadata used to build target files...
Compress the target_files dir into zip file
/home/android/patchrom/htc_e8
Build full ota package: /home/android/patchrom/htc_e8/stockrom.zip

It looks a memory issue, I will try to add more memory
thanks alot.

**Comment by larnk** [comment]
additional information:
I traced the linkinfo.txt, getfilesysteminfo runs error,only those words in linkinfo.txt:
error: only position independent executables (PIE) are supported.

system release is Android 5.0
