### ISSUE TITLE
miui-framework  prob v6

### ISSUE THREAD

**Issue by Zoldyck07** [MiCode/patchrom#81]
how to fix this?

> > > build out/MiuiFramework.apk...
> > > cp: cannot stat ‘MiuiFramework’: No such file or directory
> > > /home/alfa/patchrom/build/porting.mk:326: recipe for target 'out/MiuiFramework.apk' failed
> > > make: **\* [out/MiuiFramework.apk] Error

**Comment by Omnioculars** [comment]
refer to patchrom_nexus5

**Comment by Zoldyck07** [comment]
give the detail bro ? :D

**Comment by Zoldyck07** [comment]
I  skip that one by delete MiuiFramework from makefile 
now I got this /
Traceback (most recent call last):
  File "/home/alfa/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/alfa/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/alfa/patchrom/tools/releasetools/ota_from_target_files", line 401, in WriteFullOTAPackage
    device_specific.FullOTA_Assertions()
  File "/home/alfa/patchrom/tools/releasetools/common.py", line 690, in FullOTA_Assertions
    return self._DoCall("FullOTA_Assertions")
  File "/home/alfa/patchrom/tools/releasetools/common.py", line 679, in _DoCall
    getattr(self.miui_module, function_name)(_((self,) + args), *_kwargs)
  File "/home/alfa/patchrom/tools/releasetools/miui_releasetools.py", line 6, in FullOTA_Assertions
    info.script.Mount("/data")
  File "/home/alfa/patchrom/tools/releasetools/edify_generator.py", line 140, in Mount
    p = fstab[mount_point]
KeyError: '/data'
/home/alfa/patchrom/build/porting.mk:439: recipe for target 'fullota' failed
make: **\* [fullota] Error 1

**Comment by Omnioculars** [comment]
Reset MiuiFramework in makefile, can't delete it.
And check the file metadata/recovery.fstab.

**Comment by Zoldyck07** [comment]
yup i fixed recovery.fstab 
now I'm facing this 
Traceback (most recent call last):
  File "/home/alfa/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/alfa/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/alfa/patchrom/tools/releasetools/ota_from_target_files", line 432, in WriteFullOTAPackage
    Item.GetMetadata(input_zip)
  File "/home/alfa/patchrom/tools/releasetools/ota_from_target_files", line 163, in GetMetadata
    name, uid, gid, mode = columns[:4]
ValueError: need more than 2 values to unpack
/home/alfa/patchrom/build/porting.mk:439: recipe for target 'fullota' failed
make: **\* [fullota] Error 1

**Comment by rajesheber** [comment]
even i face the same issue. any solutions to this

**Comment by ghost** [comment]
So extracting errors depend of recovery.fstab? consider i unmount data partition from cwm and fetch this error during patchrom for samsung galaxy s2 plus
  File "/home/haky86/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/haky86/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/haky86/patchrom/tools/releasetools/ota_from_target_files", line 401, in WriteFullOTAPackage
    device_specific.FullOTA_Assertions()
  File "/home/haky86/patchrom/tools/releasetools/common.py", line 690, in FullOTA_Assertions
    return self._DoCall("FullOTA_Assertions")
  File "/home/haky86/patchrom/tools/releasetools/common.py", line 679, in _DoCall
    getattr(self.miui_module, function_name)(_((self,) + args), *_kwargs)
  File "/home/haky86/patchrom/tools/releasetools/miui_releasetools.py", line 6, in FullOTA_Assertions
    info.script.Mount("/data")
  File "/home/haky86/patchrom/tools/releasetools/edify_generator.py", line 140, in Mount
    p = fstab[mount_point]
KeyError: '/data'

**Comment by caelin99** [comment]
@hak86 could you show you recovery fstab in the metadata folder?

**Comment by ghost** [comment]
done, i patchrom miui v6 and now v7 for s2 plus @caelin99  :+1: :)

**Comment by caelin99** [comment]
@hak86 hahaha alright! Can I ask you, have you ever had trouble with this issue?:
http://en.miui.com/forum.php?mod=viewthread&tid=150827&extra=page%3D2&mobile=2

**Comment by ghost** [comment]
to be honest, yes and no, which java use? i done everything such as workspace, fristpatch and fullota using java 7 oracle, only this error? nothing before? @caelin99

**Comment by caelin99** [comment]
@I use Java 6, but I only executed ota_target_from_phone and ota_from_target_files. I used to get an error for mounting /data, but I fixed my recovery.fstab  Now I only get ValueError

**Comment by caelin99** [comment]
@i oops i meant to tag @hak86 haha
