### ISSUE TITLE
Issue make fullota

### ISSUE THREAD

**Issue by rajesheber** [MiCode/patchrom#82]
# Am getting this error when am running "make fullota". Any solution to this .

Build full ota package: /home/rajesheber/Desktop/patchrom/patchrom_miui_oneplus_bacon/out/fullota.zip
unzipping target target-files...
using device-specific extensions in .
using prebuilt boot.img...
Traceback (most recent call last):
  File "/home/rajesheber/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/rajesheber/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/rajesheber/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 432, in WriteFullOTAPackage
    Item.GetMetadata(input_zip)
  File "/home/rajesheber/Desktop/patchrom/tools/releasetools/ota_from_target_files", line 163, in GetMetadata
    name, uid, gid, mode = columns[:4]
ValueError: need more than 2 values to unpack
# make: **\* [fullota] Error 1

**Comment by angurajveerasamy** [comment]
any solution for that
