### ISSUE TITLE
Zip is good, but no classes.dex inside, and no .odex file in the same directory

### ISSUE THREAD

**Issue by Jaskaranbir** [MiCode/patchrom#85]
Used AOSP source code as base to build. Steps for building->

`cd Patchrom`
`source build/envsetup.sh`
`mkdir xDevice`
`cd xDevice`

made a new makefile as follows:

```
# The original zip file, MUST be specified by each product
local-zip-file     := stockrom.zip

# The output zip file of MIUI rom, the default is porting_miui.zip if not specified
local-out-zip-file := MIUI_xDevice.zip

# the location for local-ota to save target-file
local-previous-target-dir := 

# All apps from original ZIP, but has smali files chanded
local-modified-apps :=

local-modified-jars :=

# All apks from MIUI
local-miui-removed-apps :=  GameCenter MiFinance MiLinkService Mipay Email CloudService BugReport MiuiSuperMarket PaymentService Updater VoiceAssist

#local-miui-modified-apps := AntiSpam Backup Browser Calculator Calendar CalendarProvider Contacts ContactsProvider DeskClock DownloadProvider DownloadProviderUi FileExplorer MiuiCompass MiuiGallery MiuiHome MiuiSystemUI MiuiVideo MiWallpaper Mms Music NetworkAssistant2 Notes PackageInstaller Phone Provision QuickSearchBox Settings SoundRecorder TelephonyProvider ThemeManager VpnDialogs Weather WeatherProvider XiaomiServiceFramework YellowPage

local-phone-apps := Camera2 Bluetooth HTMLViewer KeyChain LatinIME NfcNci PacProcessor \
        UserDictionaryProvider WAPPushManager

local-phone-priv-apps := BackupRestoreConfirmation DefaultContainerService FusedLocation \
        ExternalStorageProvider InputDevices OneTimeInitializer ProxyHandler SharedStorageBackup \
        Shell Tag VpnDialogs

local-density := XHDPI

# To include the local targets before and after zip the final ZIP file, 
# and the local-targets should:
# (1) be defined after including porting.mk if using any global variable(see porting.mk)
# (2) the name should be leaded with local- to prevent any conflict with global targets
local-pre-zip := adjust_apps_location
local-after-zip:= 

# The local targets after the zip file is generated, could include 'zip2sd' to 
# deliver the zip file to phone, or to customize other actions

include $(PORT_BUILD)/porting.mk

adjust_apps_location:
    mv $(ZIP_DIR)/system/app/QuickSearchBox.apk $(ZIP_DIR)/system/priv-app/QuickSearchBox.apk

local-pre-zip-misc:
    cp other/spn-conf.xml $(ZIP_DIR)/system/etc/spn-conf.xml
    cp other/apns-conf.xml $(ZIP_DIR)/system/etc/apns-conf.xml
    cp other/system_fonts.xml $(ZIP_DIR)/system/etc/system_fonts.xml

    @echo Add missing icons
    cp -f other/icons $(ZIP_DIR)/system/media/theme/default/icons
    cp other/extras/miui_mod_icons/*.png $(ZIP_DIR)/system/media/theme/miui_mod_icons/

    @echo DalvikVM Build 28 Qualcomm Optimized
    cp -f other/dalvikvm $(ZIP_DIR)/system/bin/dalvikvm
    cp -f other/dexopt $(ZIP_DIR)/system/bin/dexopt
    cp -f other/libdvm.so $(ZIP_DIR)/system/lib/libdvm.so
    cp -f other/libqc-opt.so $(ZIP_DIR)/system/lib/libqc-opt.so
#   cp -f other/extras/lock_wallpaper $(ZIP_DIR)/system/media/theme/default/lock_wallpaper

    @echo Update bootanimation
    rm $(ZIP_DIR)/system/bin/bootanimation
    cp other/bootanimation $(ZIP_DIR)/system/bin/bootanimation
    cp -f other/bootanimation.zip $(ZIP_DIR)/system/media/bootanimation.zip

    @echo Remove usless stuff
    rm -rf $(ZIP_DIR)/data/miui/apps/*.apk
    rm -rf $(ZIP_DIR)/system/media/video/*.mp4
    rm -rf $(ZIP_DIR)/system/tts/lang_pico/*.bin
```

 `adb reboot recovery`
`../tools/releasetools/ota_target_from_phone -r` (flashed the "stockrom.zip" which was generated. It worked fine).
`make workspace`
`make firstpatch` (strangely, there were NO rejects! All folders under temp/rejects were empty having no files)
`make zipfile`

Flashed the zip file, got a bootloop with following errors at logcat:

```
I/dalvikvm( 2221): Zip is good, but no classes.dex inside, and no .odex file in the same directory
W/PackageManager( 2221): Exception reading jar: /system/framework/framework-ext-res.apk
W/PackageManager( 2221): java.io.IOException: /system/framework/framework-ext-res.apk
W/PackageManager( 2221):        at dalvik.system.DexFile.isDexOptNeeded(Native Method)
W/PackageManager( 2221):        at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:1243)
W/PackageManager( 2221):        at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:1042)
W/PackageManager( 2221):        at com.android.server.ServerThread.initAndLoop(SystemServer.java:241)
W/PackageManager( 2221):        at com.android.server.SystemServer.main(SystemServer.java:1179)
W/PackageManager( 2221):        at java.lang.reflect.Method.invokeNative(Native Method)
W/PackageManager( 2221):        at java.lang.reflect.Method.invoke(Method.java:515)
W/PackageManager( 2221):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/PackageManager( 2221):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/PackageManager( 2221):        at dalvik.system.NativeStart.main(Native Method)
```

=============(skip some log lines)===============

```
I/SystemServer( 2221): System Content Providers
E/ActivityThread( 2221): Failed to find provider info for settings
E/System  ( 2221): ******************************************
E/System  ( 2221): ************ Failure starting core service
E/System  ( 2221): java.lang.NullPointerException
E/System  ( 2221):      at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:948)
E/System  ( 2221):      at android.provider.Settings$Secure.getStringForUser(Settings.java:2951)
E/System  ( 2221):      at android.provider.Settings$Secure.getIntForUser(Settings.java:3055)
E/System  ( 2221):      at android.provider.Settings$Secure.getInt(Settings.java:3044)
E/System  ( 2221):      at com.android.server.am.CoreSettingsObserver.populateCoreSettings(CoreSettingsObserver.java:93)
E/System  ( 2221):      at com.android.server.am.CoreSettingsObserver.sendCoreSettings(CoreSettingsObserver.java:70)
E/System  ( 2221):      at com.android.server.am.CoreSettingsObserver.<init>(CoreSettingsObserver.java:55)
E/System  ( 2221):      at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:8084)
E/System  ( 2221):      at com.android.server.ServerThread.initAndLoop(SystemServer.java:271)
E/System  ( 2221):      at com.android.server.SystemServer.main(SystemServer.java:1179)
E/System  ( 2221):      at java.lang.reflect.Method.invokeNative(Native Method)
E/System  ( 2221):      at java.lang.reflect.Method.invoke(Method.java:515)
E/System  ( 2221):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/System  ( 2221):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/System  ( 2221):      at dalvik.system.NativeStart.main(Native Method)
I/SystemServer( 2221): Input Method Service
W/InputMethodManagerService( 2221): Couldn't create dir.: /data/system/inputmethod
E/ActivityThread( 2221): Failed to find provider info for settings
F/SystemServer( 2221): BOOT FAILURE starting Input Manager Service
F/SystemServer( 2221): java.lang.NullPointerException
F/SystemServer( 2221):  at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:948)
F/SystemServer( 2221):  at android.provider.Settings$Secure.getStringForUser(Settings.java:2951)
F/SystemServer( 2221):  at com.android.internal.inputmethod.InputMethodUtils$InputMethodSettings.getSelectedInputMethod(InputMethodUtils.java:922)
F/SystemServer( 2221):  at com.android.server.InputMethodManagerService.<init>(InputMethodManagerService.java:683)
F/SystemServer( 2221):  at com.android.server.ServerThread.initAndLoop(SystemServer.java:368)
F/SystemServer( 2221):  at com.android.server.SystemServer.main(SystemServer.java:1179)
F/SystemServer( 2221):  at java.lang.reflect.Method.invokeNative(Native Method)
F/SystemServer( 2221):  at java.lang.reflect.Method.invoke(Method.java:515)
F/SystemServer( 2221):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
F/SystemServer( 2221):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
F/SystemServer( 2221):  at dalvik.system.NativeStart.main(Native Method)
W/SystemServer( 2221): ***********************************************
I/SystemServer( 2221): Accessibility Manager
F/SystemServer( 2221): BOOT FAILURE making display ready
F/SystemServer( 2221): java.lang.NullPointerException
F/SystemServer( 2221):  at com.android.server.ServerThread.initAndLoop(SystemServer.java:385)
F/SystemServer( 2221):  at com.android.server.SystemServer.main(SystemServer.java:1179)
F/SystemServer( 2221):  at java.lang.reflect.Method.invokeNative(Native Method)
F/SystemServer( 2221):  at java.lang.reflect.Method.invoke(Method.java:515)
F/SystemServer( 2221):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
F/SystemServer( 2221):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
F/SystemServer( 2221):  at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime( 2221): Shutting down VM
W/dalvikvm( 2221): threadid=1: thread exiting with uncaught exception (group=0x4160cba8)
I/Process ( 2221): Sending signal. PID: 2221 SIG: 9
W/SystemServer( 2221): ***********************************************
E/AndroidRuntime( 2221): *** FATAL EXCEPTION IN SYSTEM PROCESS: main
E/AndroidRuntime( 2221): java.lang.NullPointerException
E/AndroidRuntime( 2221):        at com.android.server.am.ActivityManagerService.showBootMessage(ActivityManagerService.java)
E/AndroidRuntime( 2221):        at com.android.server.ServerThread.initAndLoop(SystemServer.java:397)
E/AndroidRuntime( 2221):        at com.android.server.SystemServer.main(SystemServer.java:1179)
E/AndroidRuntime( 2221):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2221):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2221):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 2221):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 2221):        at dalvik.system.NativeStart.main(Native Method)
I/ServiceManager(  169): service 'permission' died
I/ServiceManager(  169): service 'entropy' died
I/ServiceManager(  169): service 'sensorservice' died
I/ServiceManager(  169): service 'gfxinfo' died
I/ServiceManager(  169): service 'procstats' died
I/ServiceManager(  169): service 'telephony.registry' died
I/ServiceManager(  169): service 'usagestats' died
I/ServiceManager(  169): service 'appops' died
I/ServiceManager(  169): service 'display' died
I/ServiceManager(  169): service 'scheduling_policy' died
I/ServiceManager(  169): service 'batterystats' died
I/ServiceManager(  169): service 'power' died
I/ServiceManager(  169): service 'user' died
I/ServiceManager(  169): service 'package' died
I/ServiceManager(  169): service 'content' died
I/ServiceManager(  169): service 'activity' died
I/ServiceManager(  169): service 'accessibility' died
I/ServiceManager(  169): service 'dbinfo' died
I/ServiceManager(  169): service 'cpuinfo' died
I/ServiceManager(  169): service 'account' died
I/ServiceManager(  169): service 'meminfo' died
E/installd(  179): eof
E/installd(  179): failed to read size
I/installd(  179): closing connection
I/Zygote  ( 1964): Exit zygote because system server (2221) has terminated
I/ServiceManager(  169): service 'media.audio_flinger' died
I/ServiceManager(  169): service 'media.player' died
I/ServiceManager(  169): service 'media.camera' died
I/Netd    ( 2246): Netd 1.0 starting
W/InterfaceController( 2246): Warning (dlopen failed: library "/system/lib/libnetcmdiface.so" not found) while opening the net interface command library
```

===============skip more log lines================

```
I/ActivityManager( 2501): Memory class: 192
W/System.err( 2501): java.io.FileNotFoundException: device_features/mako.xml
W/System.err( 2501):    at android.content.res.AssetManager.openAsset(Native Method)
W/System.err( 2501):    at android.content.res.AssetManager.open(AssetManager.java:316)
W/System.err( 2501):    at android.content.res.AssetManager.open(AssetManager.java:290)
W/System.err( 2501):    at miui.util.FeatureParser.read(FeatureParser.java:138)
W/System.err( 2501):    at miui.util.FeatureParser.<clinit>(FeatureParser.java:54)
W/System.err( 2501):    at android.provider.MiuiSettings$System.isScreenPaperModeSupported(MiuiSettings.java:927)
W/System.err( 2501):    at com.android.server.am.ExtraActivityManagerService.<clinit>(ExtraActivityManagerService.java:188)
W/System.err( 2501):    at com.android.server.am.ActivityManagerService.<init>(ActivityManagerService.java:1970)
W/System.err( 2501):    at com.android.server.am.ActivityManagerService.<init>(ActivityManagerService.java:203)
W/System.err( 2501):    at com.android.server.am.ActivityManagerService$AThread.run(ActivityManagerService.java:1847)
```

The ROM I was building from is stock AOSP kitkat-mr1-release (Deodexed) without any modifications.

Also, while running `../tools/releasetools/ota_target_from_phone -r`, in the end it gave error->

```
Remount /system to be writable
remount of vendor failed: Success
remount failed
```

(everything else was fine)

**Comment by Jaskaranbir** [comment]
Problem Solved.

It appears that default updater-script generated by patchrom doesn't contain enough permissions. Manually adding permissions fixed issue.

Another problem is MIUI not working with ART. Gives VM related errors (as seen above). Switching to Dalvic fixed those.

**Comment by rahulrdhobi** [comment]
@Jaskaranbir I'm also facing same issue, can you tell me which changes you have done?

**Comment by Jaskaranbir** [comment]
I just manually inserted the permissions in updater-script by first using AOSP updater-script as base and making relevant changes.

You can have a look at my [repository](https://github.com/Jaskaranbir/MIUI_Patchrom-Nexus4) if you want to. Here's the fixed [updater-script](https://github.com/Jaskaranbir/MIUI_Patchrom-Nexus4/blob/v6-kitkat/fixes/META-INF/com/google/android/updater-script) in my case.

**Comment by rahulrdhobi** [comment]
@Jaskaranbir: I think you are talking about set_metadata for permission,I have done this but still having same issue

**Comment by Jaskaranbir** [comment]
Ah sorry about that, almost forgot to mention..... Besides that there were some libraries too that I had to fix. Like libsql (maybe there were couple more, but this is all I remember. It has been fair deal of time since I last worked on patchrom). I fixed them by copying the nexus 5 library alternatives to my nexus 4 (libraries like libsql are not really strictly **that** device specific). You can probably try something similar if you get the same log at boot.

**Comment by rahulrdhobi** [comment]
@Jaskaranbir : But I think there is no relation between libsql and framework-ext-res.apk, BTW do you know how to solve below error?

`I/dalvikvm(  525): Zip is good, but no classes.dex inside, and no .odex file in the same directory
W/PackageManager(  525): Exception reading jar: /system/framework/framework-ext-res.apk
W/PackageManager(  525): java.io.IOException: /system/framework/framework-ext-res.apk
W/PackageManager(  525):    at dalvik.system.DexFile.isDexOptNeeded(Native Method)
W/PackageManager(  525):    at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:1249)
W/PackageManager(  525):    at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:1048)
W/PackageManager(  525):    at com.android.server.ServerThread.initAndLoop(SystemServer.java:245)
W/PackageManager(  525):    at com.android.server.SystemServer.main(SystemServer.java:1222)
W/PackageManager(  525):    at java.lang.reflect.Method.invokeNative(Native Method)
W/PackageManager(  525):    at java.lang.reflect.Method.invoke(Method.java:515)
W/PackageManager(  525):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
W/PackageManager(  525):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)`

**Comment by Jaskaranbir** [comment]
@rahulrdhobi framework-ext-res.apk or franework-res.apk _arent supposed to have any dex or odex_. Its the framework jar files that have classes (aka smali files). And these jar files first pre-load necessary classes. So it is possible that something is causing them to not load. Hence, how about trying to fix up libraries first?
