### ISSUE TITLE
Error  in file  tools/apkcerts.py running '../tools/releasetools/ota_target_from_phone -r'

### ISSUE THREAD

**Issue by larnk** [MiCode/patchrom#88]
Remount /system to be writable
remount succeeded
Run getfilesysteminfo to build filesystem_config.txt
100 KB/s (5572 bytes in 0.054s)
Run getfilesysteminfo and recoverylink.py to recover symlink
Recovery link files success
Build apkcerts.txt
852 KB/s (219548 bytes in 0.251s)
Traceback (most recent call last):
  File "/home/android/patchrom/tools/apkcerts.py", line 65, in <module>
    main()
  File "/home/android/patchrom/tools/apkcerts.py", line 34, in main
    name = getName(pkg.attributes["codePath"].value)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 522, in **getitem**
    return self._attrs[attname_or_tuple]
KeyError: 'codePath'

**Comment by wzonxin** [comment]
I have meet a similar problem

unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
Traceback (most recent call last):
  File "/home/xin/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/xin/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/xin/patchrom/tools/releasetools/ota_from_target_files", line 401, in WriteFullOTAPackage
    device_specific.FullOTA_Assertions()
  File "/home/xin/patchrom/tools/releasetools/common.py", line 690, in FullOTA_Assertions
    return self._DoCall("FullOTA_Assertions")
  File "/home/xin/patchrom/tools/releasetools/common.py", line 679, in _DoCall
    getattr(self.miui_module, function_name)(_((self,) + args), *_kwargs)
  File "/home/xin/patchrom/tools/releasetools/miui_releasetools.py", line 6, in FullOTA_Assertions
    info.script.Mount("/data")
  File "/home/xin/patchrom/tools/releasetools/edify_generator.py", line 140, in Mount
    p = fstab[mount_point]
KeyError: '/data'
