### ISSUE TITLE
Issue When "Make Workspace"

### ISSUE THREAD

**Issue by Javier-Alonso** [MiCode/patchrom#89]
I'm porting Miuiv6.
I tried to extract files from phone, but i got this:

using prebuilt boot.img...
Traceback (most recent call last):
 File "/home/develop/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
 main(sys.argv[1:])
 File "/home/develop/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
 WriteFullOTAPackage(input_zip, output_zip)
 File "/home/develop/patchrom/tools/releasetools/ota_from_target_files", line 432, in WriteFullOTAPackage
 Item.GetMetadata(input_zip)
 File "/home/develop/patchrom/tools/releasetools/ota_from_target_files", line 163, in GetMetadata
 name, uid, gid, mode = columns[:4]
ValueError: need more than 2 values to unpack

(I'm using CyanogenMod 11 as base). So, I get CyanogenMod11.zip and I renamed it to "stockrom.zip" and I pasted it into my device folder.
That doesn't work, so I copied like on nexus5 folder, copying boot.img and system folder in stockrom folder.
Then, when I tried to make workspace, I got this:

»> Install framework resources for apktool...
/home/develop/patchrom/tools/apktool —quiet if /home/develop/patchrom/miui/HDPI/system/framework/framework-ext-res.apk
/home/develop/patchrom/tools/apktool —quiet if /home/develop/patchrom/miui/HDPI/system/app/miui.apk
/home/develop/patchrom/tools/apktool —quiet if /home/develop/patchrom/miui/HDPI/system/app/miuisystem.apk
/home/develop/patchrom/tools/apktool —quiet if /home/develop/patchrom/miui/HDPI/system/framework/framework-res.apk -t miui
Apktool v1.5.1 - a tool for reengineering Android apk files
Copyright 2010 Ryszard Wiśniewski brut.alll@gmail.com
with smali v1.4.1, and baksmali v1.4.1
Updated by @iBotPeaches connor.tumbleson@gmail.com 
Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

Usage: apktool [-q|--quiet OR -v|--verbose] COMMAND [...]

COMMANDs are:

 d[ecode] [OPTS] <file.apk> [<dir>]
 Decode <file.apk> to <dir>.

 OPTS:

 -s, —no-src
 Do not decode sources.
 -r, —no-res
 Do not decode resources.
 -d, —debug
 Decode in debug mode. Check project page for more info.
 -b, —no-debug-info
 Baksmali — don't write out debug info (.local, .param, .line, etc.)
 -f, —force
 Force delete destination directory.
 -t <tag>, —frame-tag <tag>
 Try to use framework files tagged by <tag>.
 —frame-path <dir>
 Use the specified directory for framework files
 —keep-broken-res
 Use if there was an error and some resources were dropped, e.g.:
 "Invalid config flags detected. Dropping resources", but you
 want to decode them anyway, even with errors. You will have to
 fix them manually before building.

 b[uild] [OPTS] [<app_path>] [<out_file>]
 Build an apk from already decoded application located in <app_path>.

 It will automatically detect, whether files was changed and perform
 needed steps only.

 If you omit <app_path> then current directory will be used.
 If you omit <out_file> then <app_path>/dist/<name_of_original.apk>
 will be used.

 OPTS:

 -f, —force-all
 Skip changes detection and build all files.
 -d, —debug
 Build in debug mode. Check project page for more info.
 -a, —aapt
 Loads aapt from specified location.

 if|install-framework <framework.apk> [<tag>]
 Install framework file to your system.

For additional info, see: http://code.google.com/p/android-apktool/
For smali/baksmali info, see: http://code.google.com/p/smali/
make: **\* [out/apktool-if] Error 1

I need help. Sorry for my bad english

**Comment by Javier-Alonso** [comment]
Solved! I needed Java 7
