### ISSUE TITLE
Please help  I am facing this issue 

### ISSUE THREAD

**Issue by TheLazyDev** [MiCode/patchrom#90]
Build full ota package: /home/noob/patchrom/sprout/out/fullota.zip
unzipping target target-files...
using device-specific extensions in .
Traceback (most recent call last):
  File "/home/noob/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/noob/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/noob/patchrom/tools/releasetools/ota_from_target_files", line 382, in WriteFullOTAPackage
    metadata = {"post-build": GetBuildProp("ro.build.fingerprint", input_zip),
  File "/home/noob/patchrom/tools/releasetools/ota_from_target_files", line 492, in GetBuildProp
    bp = z.read("SYSTEM/build.prop")
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'SYSTEM/build.prop' in the archive"
make: **\* [fullota] Error 1
noob@MyLife:~/patchrom/sprout$

**Comment by Jaskaranbir** [comment]
You sure you are using python2? Because python3 is not supported by build scripts....
