### ISSUE TITLE
Error while ota_from_target_files

### ISSUE THREAD

**Issue by dkbhadeshiya** [MiCode/patchrom#95]
I was extracting stock rom from device, while I got this error at the last stage while creating stockrom.zip

```
$ ../tools/releasetools/ota_target_from_phone -r
Wait for the device to be online...
Copy target file template into current working directory
Dump bootimage from device
3062 KB/s (10444800 bytes in 3.330s)
Extract recovery.fstab from device
mount: mounting /dev/block/mmcblk0p36 on /system failed: Device or resource busy
mount: mounting /dev/block/mmcblk0p38 on /data failed: Device or resource busy
Extract the whole /system from device
pull: building file list...
~
~
Compress the target_files dir into zip file
/home/dkbhadeshiya/work/patchrom/titan
Build full ota package: /home/dkbhadeshiya/work/patchrom/titan/stockrom.zip
unzipping target target-files...
using device-specific extensions in .
unable to load device-specific module; assuming none
Traceback (most recent call last):
  File "/home/dkbhadeshiya/work/patchrom/tools/releasetools/ota_from_target_files", line 884, in <module>
    main(sys.argv[1:])
  File "/home/dkbhadeshiya/work/patchrom/tools/releasetools/ota_from_target_files", line 852, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "/home/dkbhadeshiya/work/patchrom/tools/releasetools/ota_from_target_files", line 401, in WriteFullOTAPackage
    device_specific.FullOTA_Assertions()
  File "/home/dkbhadeshiya/work/patchrom/tools/releasetools/common.py", line 690, in FullOTA_Assertions
    return self._DoCall("FullOTA_Assertions")
  File "/home/dkbhadeshiya/work/patchrom/tools/releasetools/common.py", line 679, in _DoCall
    getattr(self.miui_module, function_name)(*((self,) + args), **kwargs)
  File "/home/dkbhadeshiya/work/patchrom/tools/releasetools/miui_releasetools.py", line 6, in FullOTA_Assertions
    info.script.Mount("/data")
  File "/home/dkbhadeshiya/work/patchrom/tools/releasetools/edify_generator.py", line 142, in Mount
    (p.fs_type, common.PARTITION_TYPES[p.fs_type],
KeyError: 'f2fs'
```

**Comment by Jaskaranbir** [comment]
seems like F2FS file system is not supported by patchrom.
Try the usual ext4 etc?

**Comment by shumxin** [comment]
May fstype like f2fs in your recovery.fstab,you can try ro change fsfs to normal fstype like ext4
